### ISSUE TITLE
fail to reload the data 

### ISSUE THREAD

**Issue by shine333** [immunomind/immunarch#1]
I just followed the instruction, created a metadata.txt in the folder containing the vdjtools output --TCR clonotypes data  ,but when I try to reload the data " immdata <- repLoad("data_vdjtool","vdjtools")", the error come up : 
Parsing data_vdjtool/c.1.txt -- vdjtools
Error in `$<-.data.frame`(`*tmp*`, "Proportion", value = numeric(0)) :
  replacement has 0 rows, data has 143053.
But when I try the tcR package : "immdata <-parse.folder()", it works.

**Comment by vadimnazarov** [comment]
Hi, can you please attach first 3-5 lines from your file `data_vdjtool/c.1.txt`?

Also can you please try 
`repLoad("data_vdjtool")`

and see if it works

**Comment by shine333** [comment]
Still didn't work...
> head(c1)
    count       freq                                        cdr3nt
1 1170631 0.07028632             TGTGCCAGCAGTGCGGCAGATGGGCTGTTTTTT
2  579774 0.03481044          TGTGCCAGCCGGACAGATCACTATGGCTACACCTTC
3  551102 0.03308893 TGTGCCAGCACGCTGGACAGCTATAGCAATCAGCCCCAGCATTTT
4  511834 0.03073123       TGTGCCACCAGTGATTACGGGGTCGGTGGCTACACCTTC
5  367842 0.02208575 TGTGCCAGCACGCTGGACAGCTATAGCAATCAGCCCCAGCATTTT
6  231363 0.01389136    TGTGCCACCAGCCCCCCCGACAGGGAAGAGACCCAGTACTTC
           cdr3aa        v     d       j VEnd DStart DEnd JStart
1     CASSAADGLFF TRBV12-3 TRBD2 TRBJ2-2   11     12   18     23
2    CASRTDHYGYTF  TRBV6-1 TRBD1 TRBJ1-2    8     10   15     19
3 CASTLDSYSNQPQHF  TRBV6-1 TRBD1 TRBJ1-5    9     14   19     23
4   CATSDYGVGGYTF TRBV24-1 TRBD1 TRBJ1-2   15     18   21     26
5 CASTLDSYSNQPQHF  TRBV6-2 TRBD1 TRBJ1-5    9     14   19     23
6  CATSPPDREETQYF   TRBV15 TRBD1 TRBJ2-5   11     18   24     25
> test <- repLoad("data_vdjtool")
Parsing data_vdjtool ...
Parsing data_vdjtool/1.txt -- vdjtools
Error in `$<-.data.frame`(`*tmp*`, "Proportion", value = numeric(0)) :
  replacement has 0 rows, data has 143053

**Comment by vadimnazarov** [comment]
Thank you, can you please send 3-5 lines from the file as a file? I just a want a tiny copy of your file to fully reproduce your error and I don't need all lines, just first lines with a header and a couple of clonotypes

**Comment by shine333** [comment]
Please check the file. Thank you .
------------------ Original ------------------

**Comment by vadimnazarov** [comment]
Hi, I think the file didnt get attached, can you please attach it via GitHub interface? You just need drag-n-drop the file into the comment section, and that's it, I will check it ASAP.

**Comment by shine333** [comment]
[c1.txt](https://github.com/immunomind/immunarch/files/3042215/c1.txt)

**Comment by vadimnazarov** [comment]
Hi, please check the new version here, I fixed it:
[immunarch_0.3.1.tar.gz](https://github.com/immunomind/immunarch/files/3042383/immunarch_0.3.1.tar.gz)

Download the file and install it as usual:
```
devtools::install_local("path/to/your/folder/with/immunarch.tar.gz", dependencies=T)
```

**Comment by vadimnazarov** [comment]
Closing for now, seems working. Please re-open it and the issue persists.
