### ISSUE TITLE
Some questions about the visualization by group

### ISSUE THREAD

**Issue by YiweiNiu** [immunomind/immunarch#10]
Hi,

Thanks for this cool tool!

I have two questions about the visualization of `.by` group data.

Here is my data and metadata.

```R
> names(tcr$data)
 [1] "0619_LN1" "0619_LN2" "0619_LN3" "0619_LN4" "0619_LN5" "0619_LN6" "0619_N1"  "0619_N2"  "0619_N3"  "0619_N4"  "0619_N5" 
[12] "0619_P1"

> tcr$meta
# A tibble: 12 x 4
   Sample   patient source tissue  
   <chr>    <chr>   <chr>  <chr>   
 1 0619_LN1 S0619   LN1    LN      
 2 0619_LN2 S0619   LN2    LN      
 3 0619_LN3 S0619   LN3    LN      
 4 0619_LN4 S0619   LN4    LN      
 5 0619_LN5 S0619   LN5    LN      
 6 0619_LN6 S0619   LN6    LN      
 7 0619_N1  S0619   N1     normal  
 8 0619_N2  S0619   N2     adjacent
 9 0619_N3  S0619   N3     tumor   
10 0619_N4  S0619   N4     tumor   
11 0619_N5  S0619   N5     tumor   
12 0619_P1  S0619   P1     PBMC  
```

First, I visualized the clonality by proportion.

```R
tcr.imm_pr = repClonality(tcr$data, .method = "clonal.prop")
vis(tcr.imm_pr)
```

![图片](https://user-images.githubusercontent.com/25263399/62289257-d39bbc80-b490-11e9-8b23-4c479d404478.png)

```R
vis(tcr.imm_pr, .by = 'tissue', .meta = tcr$meta, .test = F)
```

![图片](https://user-images.githubusercontent.com/25263399/62289276-e0201500-b490-11e9-945f-5a42ae27cb7e.png)

From the individual samples. "0619_N3", "0619_N4" and "0619_N5" (from tumor) all have higher values than that of "0619_P1" (from PBMC). Why does PBMC have higher value than that of tumor after using `.by = 'tissue'`?

Second, visualized the clonal space homeostasis.

```R
tcr.imm_hom = repClonality(tcr$data, .method = "homeo", .clone.types = c(Small = .0001, Medium = .001, Large = .01, Hyperexpanded = 1))
vis(tcr.imm_hom)
```

![图片](https://user-images.githubusercontent.com/25263399/62289598-b1566e80-b491-11e9-81a0-c194ee55e0cb.png)

```R
vis(tcr.imm_hom, .by = c('tissue'), .meta = tcr$meta, .test = F)
```

![图片](https://user-images.githubusercontent.com/25263399/62289600-b6b3b900-b491-11e9-870a-c02a3204cf5d.png)

In the figure of individual samples, "0619_N2" does not have "Small" clones while all others have. But in the group view, "adjacent" (from "0619_N2") has over 20% "Small" clones. Also, nearly all samples have high proportion of "Medium" clones, but only tissue "LN" shows in the group view. So, how to understand this?

I am looking forward to hearing you.

Bests,
Yiwei Niu

**Comment by vadimnazarov** [comment]
HI, thank you, will look into it and get back with updates or questions as quick as possible!

**Comment by vadimnazarov** [comment]
Hi, please update to the latest package version and check if everything is OK. The version should be 0.3.3.9006

**Comment by YiweiNiu** [comment]
Thank you for your quick reply!

The problem is solved after using the newer version.
