### ISSUE TITLE
signif.digits not working as expected

### ISSUE THREAD

**Issue by splaisan** [immunomind/immunarch#102]
from: https://immunarch.com/articles/web_only/v4_overlap.html

I do not see the difference between the two plots, many decimal subsist in both cases and sig digits are in either case much larger than 1 or 2

Can we round the numbers in the heatmap to fewer decimals that can be read?
Can we alternatively multiply the numbers by 100 (rescale!) to get larger values?

```
p1 <- vis(imm_ov2, .text.size = 2.5, .signif.digits = 1)
p2 <- vis(imm_ov2, .text.size = 2, .signif.digits = 2)

p1 + p2
```

**Comment by splaisan** [comment]
I found a workaround using ggplot2

first setting the original label font size to zero to hide the text
then add labels after reformating them

```
p14 <- vis(repovl_mori, .text.size = 0) + 
  geom_text(aes(label = sprintf("%0.4f", round(value, digits = 4))))
```

however, the proposed '.signif.digits' argument would be easier to use if it was to work

**Comment by Alexander230** [comment]
Hi, @splaisan!
My name is Aleksandr Popov, I am a developer of the Immunarch package. Thank you for using our software!

I've made an update that fixes this bug; you can try it by installing Immunarch from Github branch with the fix:

```
devtools::install_github("immunomind/immunarch", ref="siginf-digits-fix")

```
Soon I plan to merge it into development branch of Immunarch.

Best regards,
Aleksandr

**Comment by splaisan** [comment]
thanks Aleksandr, I will try this when I have a case for your package.
Best regards,
Stephane
