### ISSUE TITLE
importing IMGT files with repLoad

### ISSUE THREAD

**Issue by drossille** [immunomind/immunarch#107]
Hi, i have just installed immunarch package. I don't seem to be able to import IMGT data. 
I have downloaded the IMGT result files that i stored into a LyT1_15092 local directory. This dir contains the following files: 
![image](https://user-images.githubusercontent.com/71084754/92746047-30032800-f383-11ea-9c8a-19202b585f1c.png)
The code i have used is the follinwg, as well as the errors produced: 
![image](https://user-images.githubusercontent.com/71084754/92746210-56c15e80-f383-11ea-9aaa-62e9824fe86f.png)

It appears that the only IMGT file that the script parses is 3_Nt-sequences.txt. 
It warns of parsing failures and of Missing column names. 
The imported data is in the right format ($data + $meta) but the clumns Clones and Proportion are obviously wrong : no summary of the same clone was calculated. 
Maybe all is right, but this means then that i should first calculate the right values for these columns. 
Can you give me your insight so that i can progress on my analysis? 
Thank you.

**Comment by yujia-w** [comment]
Hello, have you solved this problem? How to use this package to import IMGT data？

**Comment by aislinnjennings** [comment]
Hi.
I've experienced the same problems with this. Any updates?


Thanks

**Comment by Alexander230** [comment]
Hi, @drossille, @yujia-w and @aislinnjennings!
My name is Aleksandr Popov, I am a developer of the Immunarch package. Thank you for using our software!

When you start the analysis with IMGT V-Quest, select the option "Download AIRR formatted results" (like shown on the picture).

![screenshot](https://user-images.githubusercontent.com/728730/137280602-fb4f4364-4624-47df-830d-c6f2c45cbfb0.png)

After the analysis, unzip the result and load tsv file to Immunarch with `repLoad` function.

If this AIRR file still doesn't open, please provide a minimal reproducible example of your data that produces error on loading.

Best regards,
Aleksandr

**Comment by aislinnjennings** [comment]
Hi Team.

Hope you are well.
I was wondering if this issue has been resolved:

https://github.com/immunomind/immunarch/issues/104

I'm also trying to determine Shannon-evenness from my dataset. If this is possible with Immunarch it would be great.

Thanks so much.
Ais

**Comment by aislinnjennings** [comment]
Hi Team.

Hope you are well. I was wondering if you can help me with something please.
When I run the following command on the practice immdata dataframe;

pr.aav <- pubRep<https://immunarch.com/reference/pubRep.html>(immdata$data, "aa+v", .verbose = F)

the result is a dataframe with the CDR3 amino acid sequence and the V gene (which is as expected and great).

However, I've found when I run the same command on my data, I obtain the CDR3 amino acid sequence and V allele as opposed to the gene.
 I'm not sure how to change this or if maybe its's a bug?

I was wondering if you have any ideas please.

Thanks a million.
Aislinn

**Comment by Alexander230** [comment]
Hi, Aislinn!

I've moved this question to a new issue: https://github.com/immunomind/immunarch/issues/302

Best regards,
Aleksandr
