### ISSUE TITLE
Number of clonotypes (or clones) plot y axis labels

### ISSUE THREAD

**Issue by veghp** [immunomind/immunarch#11]
I have 3434 cells (_clones_) in my sample, but the _clonotype_ plot obtained by
```
exp_vol = repExplore(immdata$data, .method = "volume")
vis(exp_vol)
```
shows well over 5000 _clonotypes._
The clone plot shows over 25000 clones.

See also https://immunarch.com/articles/3_basic_analysis.html where the _clonotype_ numbers are similar.

I believe there is a **bug** with y axis labels: the ticks are labelled with 2000, 4000 etc instead of the correct numbers.

See also plots of diversity estimate (e.g. Chao1) where the ticks are also labelled with 2000, 4000 etc.

**Comment by vadimnazarov** [comment]
Hi, thank you for noticing that! Can you please send me your file? Email is in the profile https://github.com/vadimnazarov
I'm not totally sure what is the bug here, however, you definitely have a distinct datasets where this bug can be revealed.

**Comment by vadimnazarov** [comment]
Ping

**Comment by vadimnazarov** [comment]
@veghp Any updates on that issue?

**Comment by veghp** [comment]
Hi, I have sent you an email on the 8th of August. Resending now.

**Comment by vadimnazarov** [comment]
Hi @veghp  , we updated the package to 0.5.4. It correctly parses and extract clonotypes. To filter clones by barcodes, use the filter_barcode function. Can you please try it and get back to us if any problems arise? Closing for now, feel free to re-open it.
