### ISSUE TITLE
How can I load repertoire data that I got from iRepertoire? I have CSV files for my data right now.

### ISSUE THREAD

**Issue by deepakphd** [immunomind/immunarch#110]
## ❓ Questions and Help
We have a set of [listed tutorials available on the website](https://immunarch.com/articles/).

**Comment by vadimnazarov** [comment]
Closing this issue for now. The next version of Immunarch will mostly support the AIRR Standard data format.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
