### ISSUE TITLE
Single chain (e.g. TRB) clone proportions are calculated based on all chain types (e.g. TRA, TRB, Multi)

### ISSUE THREAD

**Issue by ElviMagda** [immunomind/immunarch#111]
Hi,

I realized that when I load my 10xGenomics data to be read as "single" chain data, the calculated proportions are not what I expected to.
As an example, It basically takes the number of clones for a specific TRB clonotype (defined by a CDR3.aa sequence) and divides it by the total number of clonotypes, but not only taking into account the TRB chains (which is what I would like to have), but by all chains (TRA, TRB and Multi). I think this is a bit misleading. 

It would be nice if you could consider this option for the next release, please. Or is there already a way that I am not aware of?

Thank you very much!

**Comment by vadimnazarov** [comment]
Closing this issue for now. It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
