### ISSUE TITLE
Parsing mixcr files with incomplete amino acid sequences

### ISSUE THREAD

**Issue by francops1722** [immunomind/immunarch#113]
Hello, I've noticed that while using repLoad on mixcr files some clonotypes with incomplete CDR3 aminoacid sequence are removed (Ex. "CIVRVEL_GANNLFF"); Is there anyway to parse automatically files including those clonotypes? 

Thank you.

**Comment by Alexander230** [comment]
Hi, @francops1722!
My name is Aleksandr Popov, I am a developer of the Immunarch package. Thank you for using our software!

Could you, please, provide an example of your data that has removed clonotypes? It will help to find out what happened on the parsing stage.

Best regards,
Aleksandr

**Comment by francops1722** [comment]
Thanks
