### ISSUE TITLE
Integration with Seurat and barcode names

### ISSUE THREAD

**Issue by ghost** [immunomind/immunarch#117]
Hi love Immunarch! Such a great tool.

I have been using it for the analysis of clusters of B cells analysed through Seurat but when I use  integrated anchoring in Seurat the barcodes get a -1_1, -1_2 instead of the usual -1 ending and I cant then select_clusters from the data for further-down analysing with immunarch. Was wondering if you have thought about what would be the easiest way around this?

Best regards, Andri Lemarquis

**Comment by Alexander230** [comment]
Hi, @aleofifi!
My name is Aleksandr Popov, I am a developer of the Immunarch package. Thank you for using our software!

Could you, please, provide a small reproducible example of your data that causes error in select_clusters? Then I will be able to update the function to add support for this data format.

Best regards,
Aleksandr

**Comment by JonathanNoonan** [comment]
Hi Aleksandr - was there ever any update to this? Im having a similar issue. I would very much like to use Immunarch, but it's unclear how to add metadata (e.g. Custer or Patient IDs) from large Seurat objects consisting of multiple integrated CellRanger runs to an Immunarch df. 

Cheers!

**Comment by Alexander230** [comment]
Hi, @JonathanNoonan!

Unfortunately, I don't have any data with which I can repeat the loading steps and reproduce the issue. Could you, please, provide a small sample of your data? It will help me check how it works with repLoad() function. Maybe, your input format is not currently supported in Immunarch; a data sample will help to implement it in the future.

Best regards,
Aleksandr

**Comment by vadimnazarov** [comment]
Closing this issue for now. It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
