### ISSUE TITLE
Difficulties parsing .txt files from MiXCR using repLoad

### ISSUE THREAD

**Issue by michaeljamescarter** [immunomind/immunarch#12]
Hi Vadim,

I have used Immunarch previously, but can't get it to load data from my current study.

I have used MiXCR to align, assemble and export clones and alignments on bulk RNA-seq data, and have output files as .txt. Unfortunately repLoad will not parse my data either as the clones (from exportClones) or alignments (exportAlignments). 

When defining the data format (.format = "mixcr") I receive the following error message: "Error in strsplit(df[[.dalignments]], "|", T, F, T) : non-character argument".

When leaving the data format undefined I receive this message: "-- unsupported format, skipping".

For simplicity, I haven't included my metadata file in the folder of data; and have limited the contents of the folder to a single text file each time (either clones, or alignments). I have attached an example of these data in a separate email.

Your help would be much appreciated.

Thanks, Michael

**Comment by vadimnazarov** [comment]
Hi Michael, thank you for this very important issue, I received your email and we are looking into it!

**Comment by vadimnazarov** [comment]
Hi, please update to the latest package version and check if everything is OK. The version should be 0.3.3.9006

**Comment by vadimnazarov** [comment]
Fixed in the latest version (communicated via email).
