### ISSUE TITLE
Suggestions: metadata for each cell and integrate with Seurat in single-cell VDJ scenario

### ISSUE THREAD

**Issue by YiweiNiu** [immunomind/immunarch#13]
Hi immunarch developers,

Great thanks for this cool tool!

I would like to suggest two features which I think would improve the usability of `immuarch` when the input data is from single-cell.

1. Add metadata for each cell.

Now, `immuarch` reads data from samples and metadata is for each sample. In single-cell VDJ, if user want to compare clones of sub clusters of cells, they have to create another set of input files. If each cell has its own metadata, it would be much easier to compare different groups of cells.

2. Provide a small vignette or a set of functions to integrate VDJ data into Seurat object.

Nowadays, lots of researchers combine single-cell VDJ and single-cell RNA-seq analysis in their studies, and tools like [Seurat](https://satijalab.org/seurat/vignettes.html) are popular in single-cell RNA-seq data analysis. It is useful to map VDJ data to the cell clusters defined by transcriptome. There are already such tries like [this](https://www.biostars.org/p/383217/) and [this](https://www.biostars.org/p/383217/). Since `immuarch` has high-level interfaces to manipulate VDJ data from several different platforms,  it would be great that `immuarch` can provide a more elegant way to do this.

Please ignore me if you think it is trivial.

**Comment by EugeneRumynskiy** [comment]
Hello @YiweiNiu , it's been a while. Thank you for the ideas. Here is a couple of questions to clarify

First. Yep, this could be a potentially good feature. But first we need two things to understand better:
1. Potential range of typical tasks for comparison of different groups of cells. We need more examples.
2. A small sample of data for better understanding of data-problems you a trying to solve.
So, as always, we need a bit more information from you.

Second. The same as the first. We need a bit data to understand it's format, and we need use-cases. 

May be you have contacts of people who are in need of those features. It would be great to hear about their problems and see closer what are the main problems it current data-pipelines.

By the way. 'There are already such tries like this and this' - in **this and this**  the links are similar. But we caught the idea :)

**Comment by vadimnazarov** [comment]
Hi @YiweiNiu , can you please send us an example repertoire data with metadata that you want to load into R via immunarch? Do you process this data via Seurat first?

**Comment by vadimnazarov** [comment]
Closed because no response.
