### ISSUE TITLE
repLoad() function

### ISSUE THREAD

**Issue by TeresaRubio** [immunomind/immunarch#134]
## 🐛 Bug
When repLoad function loads files from MiXCR (I did not check in other formats), the column "allVHitsWithScore" is alphabeticaly ordered in the immunarch object while order by MiXCR score was spected. Then, geneUsage produces a wrong output with .ambig="maj" because the majoritary is the first alphabetically.

## To Reproduce

1. immdata <- repLoad("mixcrdata")
2. geneUsage(immdata$data, "hs.trbv", .ambig = "maj")

## Expected behavior

**MiXCR "allVHitsWithScore" column**: TRBV6-1*00(175),TRBV6-5*00(160),TRBV6-6*00(160),TRBV10-3*00(154)

**What I want**: TRBV6-1

**immunarch "V.name" column**: TRBV10-3, TRBV6-1, TRBV6-5, TRBV6-6

**What I obtain**: TRBV10-3

**Comment by vadimnazarov** [comment]
Hello @TeresaRubio and thank you so much for signing up on GitHub to open an issue, I truly appreciate it!

I'm deeply sorry for the very late response. We've been extremely busy raising investments and hiring the team after finishing UC Berkeley startup accelerator. We are finally set up for now: we grew the team from 4 to 15 amazing professionals, and raised a large investment round from great investors. Thank you so much for your patience!

We made changes to the Immunarch code to fix the issue you described. Please update to the latest development version of the package and let us know how it works. To install the development version, execute the following code:

`devtools::install_github("immunomind/immunarch", ref="dev")`

Improving upon Immunarch, we will soon release our online analytics platform for fast, effortless and code-less reproduction of impactul single-cell transcriptomics and immune repertoire publications. It's designed for researchers who spend a lot of time or energy reproducing sophisticated pipelines or analysing datasets from publications. Feel free to send us a link to publications of your interest so we can reproduce them on our platform and give you an access. 

We are more than happy to grant you an early access as our gratitude for you being a longstanding immunarch user.

We have a list of datasets from around 30 publications that we are going to make available for your exploration and analysis. As an example, we recently reproduced on a platform a paper focused on scRNAseq-based estimation of efficacy of CAR-T immunotherapy.

Please send links to support@immunomind.io. The direct link to the publication datasets would be also greatly appreciated.

**Comment by TeresaRubio** [comment]
Thank you! Now is working correctly :)

**Comment by vadimnazarov** [comment]
Great to hear that, thank YOU for letting us know about it!
