### ISSUE TITLE
Rarefaction diversity switched mean and quantile.

### ISSUE THREAD

**Issue by TobiTekath** [immunomind/immunarch#135]
## 🐛 Bug

Hi there,
I stumbled upon a bug in the rarefaction diversity estimation.

In 
https://github.com/immunomind/immunarch/blob/9dce2ea78f4fb15557e17664910f14c47caa8e63/R/diversity.R#L409-L410

the "Mean" and Quantile columns are wrongly named. The column "Mean"  should be the second column in my opinion.

Also, as far as I can tell, the quantile seems to be hardcoded in 
https://github.com/immunomind/immunarch/blob/9dce2ea78f4fb15557e17664910f14c47caa8e63/R/diversity.R#L402
although it is possible to specify custom quantiles.

## To Reproduce
```
data(immdata)
test_raref <- immunarch::repDiversity(immdata$data, .method = "raref", .col = "aa")
test_raref
```

The "mean" is always lower than the the "Q0.025".

## Expected behavior

The "mean" should be between the quantile values.

**Comment by vadimnazarov** [comment]
Hello @TobiTekath  and thank you so much for signing up on GitHub to open an issue, I truly appreciate it!

I'm deeply sorry for the very late response. We've been extremely busy raising investments and hiring the team after finishing UC Berkeley startup accelerator. We are finally set up for now: we grew the team from 4 to 15 amazing professionals, and raised a large investment round from great investors. Thank you so much for your patience!

We made changes to the Immunarch code to fix the issue you described. Please update to the latest development version of the package and let us know how it works. To install the development version, execute the following code:

`devtools::install_github("immunomind/immunarch", ref="dev")`

Improving upon Immunarch, we will soon release our online analytics platform for fast, effortless and code-less reproduction of impactul single-cell transcriptomics and immune repertoire publications. It's designed for researchers who spend a lot of time or energy reproducing sophisticated pipelines or analysing datasets from publications. Feel free to send us a link to publications of your interest so we can reproduce them on our platform and give you an access. 

We are more than happy to grant you an early access as our gratitude for you being a longstanding immunarch user.

We have a list of datasets from around 30 publications that we are going to make available for your exploration and analysis. As an example, we recently reproduced on a platform a paper focused on scRNAseq-based estimation of efficacy of CAR-T immunotherapy.

Please send links to support@immunomind.io. The direct link to the publication datasets would be also greatly appreciated.
