### ISSUE TITLE
The problem of multiple chain types

### ISSUE THREAD

**Issue by MungLAW** [immunomind/immunarch#14]
Hi,

I got a question about the chain type and the clonotype definition in the tools.

It seems that each chain (no matter TCR α/β) in the same data file will be considered one type of clonotype right, instead of considering a combination of them? 

So it means that different kind of chains should not be put in the same input file?

Are there any reference for this?

Many thanks,
Meng

**Comment by EugeneRumynskiy** [comment]
Hello @MungLAW ! Yep, each chain will be considered as one type of clonotype.

You could sent a small part of the data you are working with. It will help us to deal with input formats you are using. 

Next, it would be great to formulate data-problem you are trying to solve more specifically. May be we'll come up with a simple fix or solution to your case. But now It's hard to understand what functionality of Immunarch you are using.

**Comment by EugeneRumynskiy** [comment]
@MungLAW, we finally fixed this in 0.4.3 version. Just apply the repLoad function to your data, and it will split files automatically. Note the "_TRA" and "_TRB" at the end of samples, new "Chain" and "Source" columns.

To test this download this data from 10xGenomics official website (http://cf.10xgenomics.com/samples/cell-vdj/2.2.0/vdj_v1_hs_pan_t/vdj_v1_hs_pan_t_filtered_contig_annotations.csv)

Then apply repLoad:
tmp = repLoad("path/to/your/data/vdj_v1_hs_pan_t_filtered_contig_annotations.csv")

**Comment by vadimnazarov** [comment]
Hi @MungLAW ,

did you manage to try the new version of the package? Is it working for you?

**Comment by vadimnazarov** [comment]
Hi @MungLAW , we are closing this issue for now, feel free to re-open it if the problem still persists.
