### ISSUE TITLE
Link on homepage to CRAN is wrong since package was removed from CRAN

### ISSUE THREAD

**Issue by tillea** [immunomind/immunarch#142]
## 🚀 Feature
It would be great if you would be able to re-introduce immunarch into CRAN.

## Motivation
The Debian Med projects intends to create a Debian package from immunarch which is drastically simpler if available from CRAN.  It would be great to pick it from there.  If you do not see any chance for re-introduction please remove the link on the homepage.

Kind regards, Andreas.

**Comment by Alexander230** [comment]
We are working on restoring Immonomind on CRAN; for now I recommend to install the latest pre-release version directly from Github like described here: https://immunarch.com/articles/v1_introduction.html#latest-pre-release-on-github

**Comment by Alexander230** [comment]
Immunarch is restored on CRAN: https://cran.rstudio.com/web/packages/immunarch/
You are welcome to use it.

Best regards,
Aleksandr
