### ISSUE TITLE
Question regarding the scdata dataset

### ISSUE THREAD

**Issue by samcwj** [immunomind/immunarch#143]
Hi! Thank you so much for this very useful tool!

I have a question regarding the scdata object provided as an example dataset. It contains bc_patient and bc_cluster where each individual cell is labelled according to its barcode. May I know how these two lists can be added to the immunarch object please? I would like to do something similar with my Seurat clusters, and add cluster information (according to barcode) to my immunarch object.

Thank you!
Samuel

**Comment by NK-HD** [comment]
Would also be very interested in clarification on this :)

Appreciate it! 
Best Niklas

**Comment by leeanapeters** [comment]
Hi just wondering if this was addressed, I have the same needs. 

Thanks!

Leeana

**Comment by samcwj** [comment]
Hi all, nope this hasn't been answered! Please could someone help us? Thank you!!

**Comment by useryanran** [comment]
> 大家好，不，这还没有得到回答！请问有人可以帮助我们吗？谢谢！！

Can this link help you?
https://immunarch.com/articles/web_only/v21_singlecell.html

**Comment by vadimnazarov** [comment]
Closing this issue for now. It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
