### ISSUE TITLE
Problems with V-gene hits when loading MiXCR data into Immunarch

### ISSUE THREAD

**Issue by Khang-LQ** [immunomind/immunarch#153]
Hi, I am using Immunarch to analyze some BCR repertoire data and I encountered a problem with the way Immunarch handles MiXCR data.

In a MiXCR clone table there are two columns: All V gene hits with score and best V gene hits (in blue):
 
![a](https://user-images.githubusercontent.com/88042915/127169693-70f1e2a5-75fc-4e15-b867-864f378f39f8.png)

However, when loading these clone tables into Immunarch, the V gene hits are arranged in ALPHABETICAL order (in yellow):
 
![b](https://user-images.githubusercontent.com/88042915/127169798-77c4bb16-5362-4018-9590-be68712bccd2.png)

As a result, when visualizing V gene usage in Immunarch (with the option .ambig = “maj”) to choose the first hit only, the V gene frequency is distorted, no IGHV3-33 was counted even though there were thousands of hits in the MiXCR table:
 
![c](https://user-images.githubusercontent.com/88042915/127169942-50371f42-624d-4766-a270-5e0a63f9457d.png)

**My question is**: it is possible to configure Immunarch to display the V hits with the highest score according to MiXCR or rearrange the V.name column to put the best match in front so that V gene usage visualization would not be distorted because of the V gene name (using .ambig = "inc" is not practical since it involves too many combinations clutter the display).

Thank you very much for your support.

**Comment by fabio-t** [comment]
@Khang-LQ I've just tried it on my own data and it seems to get the right gene (although now I'm worried if sometimes it may take the wrong one..).

Are you using the latest release?

**Comment by fabio-t** [comment]
Ah, but I see now that I produce the mixcr tables in a different way, which may account for the different result:

`mixcr exportClones -t -o -vHit -jHit -dHit -cHit -p full -f output1.clns sample1.csv`

This adds the `bestVHit` (and correspondingly for J, D and C) column to the file, which may take precedence, in immunarch, to the `allVHitsWithScore` column. So you could try this trick as a workaround?

NB: I haven't tested if without those additional fields, with 0.6.6 what you are reporting still happens.

**Comment by Khang-LQ** [comment]
@fabio-t I updated Immunarch to version 0.6.6 and the problem has been resolved, now the V genes are listed in the order of highest score first. Previously I was working with Immunarch 0.6.5
