### ISSUE TITLE
CDR3 length with paired(?) data

### ISSUE THREAD

**Issue by npklein** [immunomind/immunarch#174]
Hi, thanks for making this tool!

I am trying to read in cellranger data from 10x following [](https://immunarch.com/articles/web_only/load_10x.html) and to do some data exploration. 

```
immdata <- repLoad('/filtered_contig_annotations.csv')
```

After repLoad, most cdr3 sequences have two sequences separated by ; (paired data?):

```
head(immdata_TCR$data$`50K_Test`$CDR3.aa)
[1] "CALMDSSYKLIF;CASSLEGGAGRFEQFF"    "CAVNLANQAGTALIF;CASSGTQTASNTEAFF" "CAVKDSNYQLIW;CSALGTYTHNEQFF"     
[4] "CAESRNAGNMLTF;CASTYRGSGEKLFF"     "CAVFGLAGTYKYIF;CASGIEQGDSPLHF"    "CILRASYGKLTF;CASSGWAGINTEAFF"   
```

When plotting the cd3 length it takes the length of CDR3.aa or CD3.nt, but because there are 2 sequences in the column these lengths are wrong

```
repExplore(immdata$data$Sample, "len",.col='aa') %>% vis() 
```

![image](https://user-images.githubusercontent.com/1576054/135255353-2c36c0b8-93fe-4a44-b94a-c917c71484e9.png)

Is there a different way to do this for this data, or am I reading in the data incorrectly?

**Comment by MVolobueva** [comment]
Hello @npklein !

Thank you for contacting us!

I am sorry you had to deal with this inconvenience.  Fixing it in the near future has been our priority.

I will get back to you with any updates.

Thank you so much for drawing our attention to this. Please contact us with any questions further along.

Best regards,
Maria Samokhina

**Comment by HongxiangXu** [comment]
I wonder if the bug was fixed? As I still met the same odd figure....
![image](https://user-images.githubusercontent.com/44562411/236626003-6b1572a8-c7ae-43c7-a4d5-176f88812835.png)

**Comment by vadimnazarov** [comment]
Closing this issue for now. It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123

**Comment by topafzd** [comment]
@vadimnazarov Hi, the latest version 0.9.1 still has this problem.

**Comment by wangtanzhang612** [comment]
I also encountered the same problem. Is it because TRA and TRB merged together?

**Comment by vadimnazarov** [comment]
Hi @topafzd @wangtanzhang612, I'm working on a new package and an update to `immunarch` that will solve this issue. Please stay tuned and check the messages `immunarch` prints on the package load – I will communicate all the updates there.
