### ISSUE TITLE
Can't load VDJtools file

### ISSUE THREAD

**Issue by f6v** [immunomind/immunarch#180]
## 🐛 Bug
First off, thanks for the package! I'm new to immune repertoire files, but it seems like my data is in VDJtools format:

> #count	freq	cdr3nt	cdr3aa	v	d	j
> 1	2.1566179055358223E-6	REDACTED	REDACTED	TRAV-10,TRAV-10D,TRAV-10N	.	TRAJ-12

Is that right, or the format is off? Because I'm getting the following error:

> == Step 1/3: loading repertoire files... ==
> 
> Processing "<initial>" ...
>   -- [1/1] Parsing "~/dev/TCR_novaseq/export/vdjtools//Clonotypes-30581-001.1 (paired).txt" -- unsupported format, skipping
> 
> == Step 2/3: checking metadata files and merging files... ==
> 
> Processing "<initial>" ...
>   -- Metadata file not found; creating a dummy metadata...
> Warning: Unknown or uninitialised column: `Sample`.
> Warning: Unknown or uninitialised column: `Sample`.
> 
> == Step 3/3: processing paired chain data... ==
> 
> Done!

The code:

```
imm_data <- repLoad(file.path(data_path, .mode = "single")
```

**Comment by lianggongzifang** [comment]
> Hi @f6v , thank you for using the package! Could you provide information on what version of VDJtools you are using please? An example of the file would be great too, as we will be able to quickly identify the issues using your file.

Hi @vadimnazarov , I have the same problem. I had load VDJtools file successfully using the version 0.6.5, but it failed using the version 0.6.7. The error is as mentioned above, "unsupported format, skipping".

**Comment by ElviMagda** [comment]
> ## 🐛 Bug
> First off, thanks for the package! I'm new to immune repertoire files, but it seems like my data is in VDJtools format:
> 
> > #count	freq	cdr3nt	cdr3aa	v	d	j
> > 1	2.1566179055358223E-6	REDACTED	REDACTED	TRAV-10,TRAV-10D,TRAV-10N	.	TRAJ-12
> 
> Is that right, or the format is off? Because I'm getting the following error:
> 
> > == Step 1/3: loading repertoire files... ==
> > Processing "" ...
> > -- [1/1] Parsing "~/dev/TCR_novaseq/export/vdjtools//Clonotypes-30581-001.1 (paired).txt" -- unsupported format, skipping
> > == Step 2/3: checking metadata files and merging files... ==
> > Processing "" ...
> > -- Metadata file not found; creating a dummy metadata...
> > Warning: Unknown or uninitialised column: `Sample`.
> > Warning: Unknown or uninitialised column: `Sample`.
> > == Step 3/3: processing paired chain data... ==
> > Done!
> 
> The code:
> 
> ```
> imm_data <- repLoad(file.path(data_path, .mode = "single")
> ```

Hi,

in case it helps, we changed the "freq" column name for "frequency" and it worked.

Best,
Elvira

**Comment by lianggongzifang** [comment]
ok, it works now! Thank you! 
![屏幕截图 2022-05-20 205830](https://user-images.githubusercontent.com/84553701/169532862-d6f46c79-b893-4bff-852c-d7a4eb079d01.jpg)

**Comment by Alexander230** [comment]
Nice, thank you for checking, I'm glad to hear that it's working now! If you have more questions, or the fix doesn't work for anyone else, feel free to reopen the issue.

Best regards,
Aleksandr
