### ISSUE TITLE
Rarefaction analysis

### ISSUE THREAD

**Issue by Lilian0296** [immunomind/immunarch#188]
Hi,

Thank you for the nice tool!
I'm now using the `repDiversity` with the `.method="raref"`. I want to ask how the data is normalized in Estimated diversity (unique clonotypes) and Sample size (clones). Thanks~

Best,
Lilian

**Comment by tsvvas** [comment]
Hi Lilian,

My name is Vasily, I am a developer of the Immunarch package. Thank you for using it!

Sorry for the late reply. The `.norm` parameter in case of `.method="raref"` normalizes the clones as percent of the largest sample's clone size. This is used mainly for visualisation.

I will close this issue now. If you will have any questions, feel free to open a new issue.

Best regards,
Vasily Tsvetkov
