### ISSUE TITLE
Hope the document can show the multisamples input workflow in 10X cellranger VDJ

### ISSUE THREAD

**Issue by honghh2018** [immunomind/immunarch#189]
Hi,
    Thanks to  develop the great tools for  immunolgical analysis of multiple data format. with the development of VDJ repertoires, it would be a milestone in years to come.
     In your vignettes, it was unclear about multiple sample workflow, while it was vital key to analyize the shared cloned, and the top clone per sample, especially 10X cellranger output format.
    Hope the multiple workflow of 10X cellranger VDJ can see on you readme.txt or other better html.
    I work for below step, it can not name the sample with what i want, while it just was using the sample name i given   
    files = c('test/Gao_M_filtered_contig_annotations.csv',
          'test/Gao_T_filtered_contig_annotations.csv')

    The tt1<-immunarch::repLoad(.path=files)
    Hope the improve.
Hope you reply
Best,
Hanhuihong

**Comment by MVolobueva** [comment]
Hi, @honghh2018!

My name is Maria Volobueva, I am the developer of Immunarch.
Thank you for using the package! Please compress the folder that you were using as input for repLoad (~/('test/ in your case) and attach it to the message, so we can reproduce the issue and help you out. You can also send the data to our tech support at support@immunomind.io.

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉
