### ISSUE TITLE
Error using repDiversity module

### ISSUE THREAD

**Issue by MapleJo** [immunomind/immunarch#19]
Hey, I had an error message using repDiversity module and I don't know how to solve the problem. The test data is using a result from Mixcr. Is there some way to pass it ? Many thanks.
![image](https://user-images.githubusercontent.com/54873363/64219241-474d4100-cef7-11e9-8896-1b51595290b1.png)

**Comment by EugeneRumynskiy** [comment]
Hello @MapleJo! Thank you for the report. Could you add some details to the description?

To reproduce the case we need all steps you made before the error. It includes:
1. Test data from mixcr
2. Full R script you've launched

**Comment by MapleJo** [comment]
Hi, thanks for reply, I think it's related with the code in diversity.R, because I have cut off the clones covered only one time, so here I got the "f1 == 0 && f2 != 0" but not included in your if else. When I added the Clones 1 It works.
![image](https://user-images.githubusercontent.com/54873363/64303958-0fa8cc80-cfbd-11e9-8af2-268fc9364fe5.png)

**Comment by EugeneRumynskiy** [comment]
Oh, really worked out. I suppose we can close the issue
