### ISSUE TITLE
paired data issue

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [immunomind/immunarch#191]
Hey everyone. 
I am trying to use this tutorial (https://immunarch.com/articles/web_only/v21_singlecell.html) in order to load my 10x TCR data in order to track clonotypes across seurat clusters (as shown at the very bottom of the tutorial)
However I face specific problems, I provide here my code (seu_all is my seurat object and the idents of the object are set as clusters):

`barcode_cluster<-Seurat::Idents(seu_all)`
`immdata_10x <- repLoad("~/sc_repertoire/scRepertoire_c57bl6j/bl6_tcr_data",.mode = "paired")`
```
== Step 1/3: loading repertoire files... ==

Processing "~/sc_repertoire/scRepertoire_c57bl6j/bl6_tcr_data" ...
  -- [1/2] Parsing "/home/testuser11/sc_repertoire/scRepertoire_c57bl6j/bl6_tcr_data/all_contig_annotations.csv" -- 10x (filt.contigs)
  [!] Removed 16155 clonotypes with no nucleotide and amino acid CDR3 sequence.                                                                                                                        
  -- [2/2] Parsing "/home/testuser11/sc_repertoire/scRepertoire_c57bl6j/bl6_tcr_data/clonotypes.csv" -- unsupported format, skipping

== Step 2/3: checking metadata files and merging files... ==

Processing "~/sc_repertoire/scRepertoire_c57bl6j/bl6_tcr_data" ...
  -- Metadata file not found; creating a dummy metadata...

== Step 3/3: processing paired chain data... ==


Done!

Warning message:
The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
```
`scdata_cl <- select_clusters(immdata_10x$data$all_contig_annotations, barcode_cluster, "Cluster")`

```
Error in select_clusters(immdata_10x$data[[1]], barcode_cluster, "Cluster") : 
  Please provide a list with both 'data' and 'meta' elements.

```

Any input would be appreciated, thanks a lot!

**Comment by MVolobueva** [comment]
Hi @christoforos-dimitropoulos!

My name is Maria Volobueva, I am the developer of Immunarch.
Thank you for using the package! Could you provide an example of the file you try to load, as we will be able to quickly identify the issues.

**Comment by christoforos-dimitropoulos** [comment]
> Hi @christoforos-dimitropoulos!
> 
> My name is Maria Volobueva, I am the developer of Immunarch. Thank you for using the package! Could you provide an example of the file you try to load, as we will be able to quickly identify the issues.

As an input I give the folder with the output of the 10x cellranger vdj pipeline.

**Comment by MVolobueva** [comment]
@christoforos-dimitropoulos,

**Comment by mbartl13** [comment]
Hi I am having a similar issue, the headers look the same to me though in the attached file.

`>immdata<-repLoad("~/TCR/")

== Step 1/3: loading repertoire files... ==

Processing "~/TCR/" ...
  -- [1/7] Parsing "C:/Users/Maggie/Documents/TCR/d0_43F_PBMC_20211209_filtered_contig_annotations.csv" -- 10x (filt.contigs)
  -- [2/7] Parsing "C:/Users/Maggie/Documents/TCR/d11_13F_PBMC_20220106_filtered_contig_annotations.csv" -- 10x (filt.contigs)
  -- [3/7] Parsing "C:/Users/Maggie/Documents/TCR/d168_13F_LN_20220128_filtered_contig_annotations.csv" -- 10x (filt.contigs)
 0s  -- [4/7] Parsing "C:/Users/Maggie/Documents/TCR/d168_13F_PBMC_20211209_filtered_contig_annotations.csv" -- 10x (filt.contigs)
  -- [5/7] Parsing "C:/Users/Maggie/Documents/TCR/d168_13F_PBMC_filtered_contig_annotations.csv" -- 10x (filt.contigs)
  -- [6/7] Parsing "C:/Users/Maggie/Documents/TCR/d176_43F_LN_20211209_filtered_contig_annotations.csv" -- 10x (filt.contigs)
  -- [7/7] Parsing "C:/Users/Maggie/Documents/TCR/d43_13F_PBMC_20211209_filtered_contig_annotations.csv" -- 10x (filt.contigs)
                                                                                             
== Step 2/3: checking metadata files and merging files... ==

Processing "~/TCR/" ...
  -- Metadata file not found; creating a dummy metadata...

== Step 3/3: processing paired chain data... ==

Done!

Warning messages:
1: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
2: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
3: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
4: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
5: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
6: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id 
7: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id `

[d0_43F_PBMC_20211209_filtered_contig_annotations.csv](https://github.com/immunomind/immunarch/files/8200402/d0_43F_PBMC_20211209_filtered_contig_annotations.csv)

**Comment by Alexander230** [comment]
Hi, @mbartl13!

Thank you very much for providing the data! Looks like this format of column names is unknown to the parser. I will work to add the support for this format in the future versions of Immunarch.

Best regards,
Aleksandr

**Comment by vadimnazarov** [comment]
Closing this issue for now. It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
