### ISSUE TITLE
Warning in Reading 10X data

### ISSUE THREAD

**Issue by HocheolJang426** [immunomind/immunarch#193]
To all,

I just load the TCR data from 10X using repLoad, but the warning massage returns;

Warning message:
The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,cdr3,cdr3_nt,reads,umis,raw_clonotype_id,raw_consensus_id 

This is my code to load data;
immdata_10x <- repLoad("/home/users/TCR/filtered_contig_annotations.csv")

what can be the problem?

**Comment by zhongll19** [comment]
To all,
I had the same problem, after using immdata1 <- repLoad('/data/path')
immdata <- repLoad('/data/Analysis/VDJ_tcr/Diversity/data',.coding = TRUE)

== Step 1/3: loading repertoire files... ==

Processing "/data/Analysis/zhongll/VDJ_tcr/Diversity/data" ...
  -- [1/4] Parsing "/data/Analysis/VDJ_tcr/Diversity/data/HGSOC_1.csv" -- 10x (filt.contigs)
  -- [2/4] Parsing "/data/Analysis/VDJ_tcr/Diversity/data/HGSOC_2.csv" -- 10x (filt.contigs)
  -- [3/4] Parsing "/data/Analysis/VDJ_tcr/Diversity/data/HGSOC_3.csv" -- 10x (filt.contigs)
  -- [4/4] Parsing "/data/Analysis/VDJ_tcr/Diversity/data/metadata.txt" -- metadata

== Step 2/3: checking metadata files and merging files... ==

Processing "/data/Analysis/VDJ_tcr/Diversity/data" ...
  -- Everything is OK!

== Step 3/3: processing paired chain data... ==

Done!

Warning messages:
1: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id
2: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id
3: The following named parsers don't match the column names: barcode,is_cell,contig_id,high_confidence,length,chain,v_gene,d_gene,j_gene,c_gene,full_length,productive,fwr1,fwr1_nt,cdr1,cdr1_nt,fwr2,fwr2_nt,cdr2,cdr2_nt,fwr3,fwr3_nt,cdr3,cdr3_nt,fwr4,fwr4_nt,reads,umis,raw_clonotype_id,raw_consensus_id,exact_subclonotype_id



Import data also changed, V.name and J.name appear as semicolon-separated names，like this：
  Clones  Proportion
1     45 0.011703511
2     27 0.007022107
                                                                                      CDR3.nt
1 TGTGCTCTGAGGTCCCTTAGGGAAACCAGTGGCTCTAGGTTGACCTTT;TGTGCCAGCAGTGACCGGGACCCTAGGGATACGCAGTATTTT
2                                                        TGTGCTGTGGGAGGGAACTTCAACAAATTTTACTTT
                          CDR3.aa         V.name    D.name         J.name V.end
1 CALRSLRETSGSRLTF;CASSDRDPRDTQYF TRAV19;TRBV6-5 None;None TRAJ58;TRBJ2-3    NA
2                    CAVGGNFNKFYF          TRAV2      None         TRAJ21    NA
  D.start D.end J.start VJ.ins VD.ins DJ.ins
1      NA    NA      NA     NA     NA     NA
2      NA    NA      NA     NA     NA     NA
                                                                                     Sequence
1 TGTGCTCTGAGGTCCCTTAGGGAAACCAGTGGCTCTAGGTTGACCTTT;TGTGCCAGCAGTGACCGGGACCCTAGGGATACGCAGTATTTT
2                                                        TGTGCTGTGGGAGGGAACTTCAACAAATTTTACTTT
    chain
1 TRA;TRB
2     TRA

packageVersion('immunarch')
[1] ‘0.6.8’

But，When the Version=0.3.3 , there is no problem .
