### ISSUE TITLE
Change the label text size/style

### ISSUE THREAD

**Issue by makarov-ccf** [immunomind/immunarch#196]
Hello members
I would like to change the style/size of the axis text
For example,
library(immunarch); 
data(immdata)
p<-repOverlap(immdata$data)
vis(p)

I tried 
vis(p, .text.size=1)
but it has no effect on axis text (sample names)

Thank you

**Comment by vadimnazarov** [comment]
Dear @makarov-ccf 

Thank you for using our package in your research! Our team truly appreciates your suggestion; it helps us improve the package. Please see the experimental branch with the functionality you requested.

To install the experimental branch: 
```
install.packages(c("devtools", "pkgload"))
devtools::install_github("immunomind/immunarch", ref="feature/heatmap-axis-text-size")
devtools::reload(pkgload::inst("immunarch"))
```

To change the text:
```
vis(p, .text.size=6, .axis.text.size=20)
```

Please post your comments, suggestions, and found bugs in this thread. Let's not close it until everything works correctly.

Would you be willing to have a short call with me in early January to discuss how we can help you more? We are working on the platform for cell therapy development using single-cell multi-omics, which Immunarch is part of, and I would sincerely appreciate your thoughts on it. My email is vadim at immunomind.io

Best,
Vadim @ CEO at Immunarch and ex-lead developer of Immunarch

**Comment by vadimnazarov** [comment]
Dear Vlad,

Great, thank you! I will close this issue for now. Feel free to open more with questions and suggestions!

I'm looking forward to your email. Happy holidays!

Best,
Vadim

**Comment by vadimnazarov** [comment]
Dear Vlad,

Thank you again for using Immunarch! We have significantly progress with our computational platform for immunotherapy development. For instance, we can automatically annotate immune cell populations in single-cell data and identify new targets. And recently, we published the results of our partner project with BC Cancer Genome Sciences Centre, Northwestern University, and Dxige Research on biomarkers of immunotherapy resistance.

Would you be open to a call with me to take a look at the platform and provide feedback?

My email is vadim at immunomind com

Thank you!
Vadim
