### ISSUE TITLE
Test issue.

### ISSUE THREAD

**Issue by EugeneRumynskiy** [immunomind/immunarch#20]
[test.txt](https://github.com/immunomind/immunarch/files/3984157/test.txt)
Testing youtrack helpdesk integration.
![index](https://user-images.githubusercontent.com/20778038/71183742-92fadf00-2289-11ea-9cd6-825a80e49620.jpeg)

**Comment by EugeneRumynskiy** [comment]
One more test.

**Comment by myrkalfr** [comment]
Second test.

**Comment by EugeneRumynskiy** [comment]
Update.

**Comment by EugeneRumynskiy** [comment]
Third ping.

**Comment by myrkalfr** [comment]
Forth ping.

**Comment by myrkalfr** [comment]
Fifth ping. With attach.

![picture2_malenkij-princ-s-_342202_p0](https://user-images.githubusercontent.com/54105400/64964294-6e1a5880-d8a3-11e9-886e-f5df7659debf.jpg)

**Comment by myrkalfr** [comment]
Sixth ping. With attach.
![picture2_malenkij-princ-s-_342202_p0](https://user-images.githubusercontent.com/54105400/64965092-095ffd80-d8a5-11e9-817e-58d910a44987.jpg)

**Comment by myrkalfr** [comment]
Seventh. Ping.
