### ISSUE TITLE
Error in library(immunarch) : there is no package called ‘immunarch’

### ISSUE THREAD

**Issue by mahlaranjeet** [immunomind/immunarch#207]
Installing 'immunarch' ...
[1/7] Installing factoextra...
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/contrib/4.1:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/PACKAGES'
[2/7] Installing fpc...
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
[3/7] Installing UpSetR...
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/contrib/4.1:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/PACKAGES'
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/contrib/4.1:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/PACKAGES'
[4/7] Installing circlize...
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/contrib/4.1:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/PACKAGES'
[5/7] Installing shinythemes...
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
[6/7] Installing ggalluvial...
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz'
Content type 'application/x-gzip' length 1777709 bytes (1.7 MB)
=====
downloaded 179 KB

[7/7] Installing immunarch...
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz' failed
In addition: Warning messages:
1: package ‘factoextra’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: package ‘fpc’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
3: package ‘UpSetR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
4: package ‘circlize’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
5: package ‘shinythemes’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
6: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 183740 != reported length 1777709
7: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘ggalluvial’ failed
Installing package into ‘/Users/rmahla-admin/Library/R/x86_64/4.1/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘flashClust’, ‘leaps’, ‘scatterplot3d’, ‘modeltools’, ‘dendextend’, ‘FactoMineR’, ‘flexmix’, ‘prabclus’, ‘diptest’, ‘GlobalOptions’, ‘factoextra’, ‘fpc’, ‘UpSetR’, ‘circlize’, ‘shinythemes’, ‘ggalluvial’

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flashClust_1.01-2.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flashClust_1.01-2.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flashClust_1.01-2.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘flashClust’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/leaps_3.1.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/leaps_3.1.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/leaps_3.1.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘leaps’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/scatterplot3d_0.3-41.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/scatterplot3d_0.3-41.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/scatterplot3d_0.3-41.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘scatterplot3d’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/modeltools_0.2-23.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/modeltools_0.2-23.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/modeltools_0.2-23.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘modeltools’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/dendextend_1.15.2.tgz'
Content type 'application/x-gzip' length 3885614 bytes (3.7 MB)
======
downloaded 511 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/contrib/4.1/dendextend_1.15.2.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 523377 != reported length 3885614
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/dendextend_1.15.2.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘dendextend’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/FactoMineR_2.4.tgz'
Content type 'application/x-gzip' length 3755097 bytes (3.6 MB)

downloaded 47 KB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/contrib/4.1/FactoMineR_2.4.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 48660 != reported length 3755097
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/FactoMineR_2.4.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘FactoMineR’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flexmix_2.3-17.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flexmix_2.3-17.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/flexmix_2.3-17.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘flexmix’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/prabclus_2.3-2.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/prabclus_2.3-2.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/prabclus_2.3-2.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘prabclus’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/diptest_0.76-0.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/diptest_0.76-0.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/diptest_0.76-0.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘diptest’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/GlobalOptions_0.1.2.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/GlobalOptions_0.1.2.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/GlobalOptions_0.1.2.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘GlobalOptions’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/factoextra_1.0.7.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/factoextra_1.0.7.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/factoextra_1.0.7.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘factoextra’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/fpc_2.2-9.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/fpc_2.2-9.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/fpc_2.2-9.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘fpc’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/UpSetR_1.4.0.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/UpSetR_1.4.0.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/UpSetR_1.4.0.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘UpSetR’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/circlize_0.4.13.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/circlize_0.4.13.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/circlize_0.4.13.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘circlize’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/shinythemes_1.2.0.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/shinythemes_1.2.0.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/shinythemes_1.2.0.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘shinythemes’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/ggalluvial_0.12.3.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘ggalluvial’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/immunarch_0.6.7.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/immunarch_0.6.7.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/immunarch_0.6.7.tgz': status was 'Couldn't resolve host name'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘immunarch’ failed

✔ Package 'immunarch' successfully installed.

library(immunarch)

Error in library(immunarch) : there is no package called ‘immunarch’

**Comment by Alexander230** [comment]
Hi, @mahlaranjeet!
My name is Aleksandr Popov, I am a developer of the Immunarch package. 
Thank you for using our software!

These are internet connection errors; please check your connection and try again.

Best regards,
Aleksandr

**Comment by vadimnazarov** [comment]
You may find these links useful for you:
- https://community.rstudio.com/t/install-packages-unable-to-access-index-for-repository-try-disabling-secure-download-method-for-http/16578
- https://stackoverflow.com/questions/38207281/unable-to-access-index-for-repository-in-r
