### ISSUE TITLE
repExplore question

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [immunomind/immunarch#216]
Hey,
I am trying to visuilize (as a pie chart for example) the clonal expansion within each sample.
Can I get a similar output to the RepEpxplore() function but instead of clone.num have clone.aa or clone.nt and also instead of the absolute clonotype counts get a persentage or normalized counts to the total reads per sample or so.
Any input will be appreciated.
Thanks a lot

**Comment by Alexander230** [comment]
Hello @christoforos-dimitropoulos,
Thank you for contacting us. My name is Aleksandr Popov, I am a developer of the Immunarch package. 
I am glad you are using our software and let's hope I can help you out.

Regarding your question, we have several options for you. You could try to use function trackClonotypes, or perform column manipulations before visualization.
If that doesn't seem to help you, can you give me a little more context on your situation? What format for output data do you want?
We will take your wish into our closest consideration as a feature to improve the package in the future.

Good luck,
Aleksandr
