### ISSUE TITLE
'repFilter exclude' removes whole samples if there isn't any match

### ISSUE THREAD

**Issue by tamaraalag** [immunomind/immunarch#221]
## 🐛 Bug
When trying to filter clonotypes that start with specific amino acid sequence to exclude them from my samples, the function repFilter does the expected job in samples that do have those clonotypes, but the samples where those clonotypes are not present are removed entirely.

## To Reproduce

1. Import data with repLoad: `immdata <- repLoad("path_directory/data/")`
2. Filter clonotypes by amino acid CDR3 sequence with repLoad: `Final_immdata <- repFilter(immdata, .method = "by.clonotype", .query = list(CDR3.aa = exclude("CALPI")), .match = "startswith")`
3. Look for a sample that did not have those clonotypes in Final_immdata

If you look at the screenshots here you can see my samples before filtering (HD61, HD64, HD65, HD66 and HD67)
<img width="360" alt="Report_bug1" src="https://user-images.githubusercontent.com/100604556/157262002-47fbbdc6-895a-4952-89e2-2db2ce9f9632.PNG">

and that HD66 doesn't have a single clonotype containing the sequence I want to exclude.
<img width="360" alt="Report_bug2" src="https://user-images.githubusercontent.com/100604556/157262713-8a1ae796-d3bb-4da4-acea-6788cc44b01b.PNG">

Then, after filtering, HD66 can't be found amongst my samples, as it has been removed entirely.
<img width="360" alt="Report_bug3" src="https://user-images.githubusercontent.com/100604556/157262959-81402e87-755f-473d-be9b-bd5c0148b5c3.PNG">

## Expected behavior
As I am using repFilter exclude, I would expect that the samples that do not have the query that I want to exclude, are left exactly as they were before using the filter.

**Comment by Alexander230** [comment]
Hi, @tamaraalag!

My name is Aleksandr Popov, I am a developer of the Immunarch package. Thank you for reporting this bug!

I've made a fix for it in `filter-bugfix` branch; soon it will make its way into `dev` branch of Immunarch.

You can use the fixed version before it make its way into release. To switch the installed version of Immunarch to `filter-bugfix` branch, use the following commands:

```
install.packages(c("devtools", "pkgload"))
devtools::install_github("immunomind/immunarch", ref="filter-bugfix")
devtools::reload(pkgload::inst("immunarch"))
```

The same commands can be used to switch to `dev` branch; just use `ref="dev"` in the 2nd line.

Best regards,
Aleksandr

**Comment by tamaraalag** [comment]
Thank you so much for fixing it, @Alexander230! 

Best regards,
Tamara

**Comment by Alexander230** [comment]
You are welcome! If you have more questions, feel free to reopen the issue and ask them.

Best regards,
Aleksandr
