### ISSUE TITLE
Support for paired data (not 10x)

### ISSUE THREAD

**Issue by dsrai** [immunomind/immunarch#222]
I'm developing a novel paired sequencing technology.

Currently my data output format looks like this;

- text document with header:

Alpha_Vgene, Beta_Vgene, Alpha_Jgene, Beta_Jgene, Beta_Dgene, Alpha_cdr3, Beta_cdr3

Is there a format I can modify this into that imunarch already supports?

If not, can support for this be made available? It would be easy for other new methods to modify their data into this format!

**Comment by Alexander230** [comment]
Hello @dsrai,

Thank you for contacting us!

Unfortunately, now we support paired data only in 10x format. If you want to load your files to Immunarch, then you need to convert the data to the 10x format.

I will get back to you with any updates when we implement more formats for paired data.

Thank you so much for drawing our attention to this. 
Do not hesitate to contact us with any questions further along.

Best regards,
Aleksandr

**Comment by dsrai** [comment]
Hi Aleksandr,

No worries! Hope it gets incorporated soon.

Could you provide an example of the 10x format?

**Comment by dsrai** [comment]
Does the program know it's paried if two rows have the same clonotype ID?
