### ISSUE TITLE
Data loading with BD Rhapsody

### ISSUE THREAD

**Issue by wajm** [immunomind/immunarch#225]
Hi, 
I'm using BD Rhapsody VDJ scRNA-seq platform, but their output is quite different from others.
So I transform the BD output into immunarch example file.
But, BD has no information about "V.end | D.start | D.end | J.start | VJ.ins | VD.ins | DJ.ins ".

In this case how I can make it for immunarch input. (just filling with "NaN")

or BD VDJ data is single cell RNA seq. 
    is it possible to custom input with single cell input type of immunarch?
   (https://immunarch.com/articles/web_only/v21_singlecell.html)

or if you have any time, check my BD example output and give a hint 
(in case please let me know where I can share file to you).  

best,
JungMo

**Comment by Alexander230** [comment]
Hi, @wajm!

Thank you for contacting us. My name is Aleksandr Popov, I am a developer of the Immunarch package. 
I am glad you are using our software and let's hope I can help you out.

Yes, if you want to load the data in csv or tsv format that is not currently supported in Immunarch, you can rename the columns to one of the supported formats (like AIRR), and fill missing columns with NA.
Also, example data is always welcome, it will help us to add support of your format to Immunarch in the future.

Best regards,
Aleksandr

**Comment by wajm** [comment]
Hi, @Alexander230!

Thanks for your kind response.

Here, "Working with sample files" section shows example files are txt files.
https://immunarch.com/articles/v2_data.html 

I thought I could make same format with my BD data and import using repLoad function.

best,
JungMo

**Comment by Alexander230** [comment]
Yes, if you reproduce this format from your data and fill missing columns with NA, repLoad() should load the data into Immunarch correctly.

Best regards,
Aleksandr

**Comment by wajm** [comment]
Ok, I'll test it.
[RhapVDJ.csv](https://github.com/immunomind/immunarch/files/8341591/RhapVDJ.csv)
An attached file is BD Rhapsody VDJ output csv file. Please check it.
Thanks a lot.
JungMo

**Comment by Alexander230** [comment]
@wajm
Thank you for providing the data! Now it only can be loaded after removing header lines and renaming the columns; we plan to add support of this format in the future.

All the best,
Aleksandr

**Comment by lysendee** [comment]
Dear Aleksandr (and team)
Thank you so much for a great package
I am also working with the BD Rhapsody, and will be using your suggestion to process the Rhapsody VDJ output to look like the immunarch example data. 
Are there still plan to update the immunearch package to work seamlessly with the BD Rhapsody output?
Anna

**Comment by Alexander230** [comment]
Hi, Anna!
Thank you for using our software!

We plan to add BD Rhapsody format support in one of the future versions of Immunarch. For now, you can try to rename columns in your file to make them look like in AIRR format; I've attached an example.

Best regards,
Aleksandr

[airr_example.zip](https://github.com/immunomind/immunarch/files/9315954/airr_example.zip)

**Comment by lysendee** [comment]
Dear Aleksandr
Thank you for a very quick response.
Sorry if this is a stupid follow up question.
I work with paired TCR data. Is there any way to add both alpha and beta paired data in the AIRR format?
Anna

**Comment by Alexander230** [comment]
Hi, Anna!

Paired read support is not implemented yet in Immunarch. We are working now on adding single cell data support with paired reads to Immunarch, so it will become available in one of the next releases.

Best regards,
Aleksandr

**Comment by Alexander230** [comment]
Hi, @wajm and @lysendee!

Unfortunately, we can't load BD Rhapsody format into Immunarch, because it's missing nucleotide sequences that are required for Immunarch functions to work. BD Rhapsody output is postprocessed; we recommend to load data from earlier stage of pipeline into Immunarch, so the data will have nucleotide sequences for clonotypes.

We plan to add support for single cell data to the next release of Immunarch; it will be possible to load the data from 10x and AIRR formats, and later we will add support for more single cell data formats.

Best regards,
Aleksandr
