### ISSUE TITLE
The 1st clone is lost after repLoad MiXCR data

### ISSUE THREAD

**Issue by Valeriy-Tereshchenko** [immunomind/immunarch#226]
## ❓ Questions and Help
We have a set of [listed tutorials available on the website](https://immunarch.com/articles/).

Hello, dear colleagues!
I am kindly asking for community support.
After repLoad folder(48 samples) with MiXCR data 1st clone in some samples is lost.
If I repLoad some problem samples separately the warning appears:
Warning messages:
1: In readLines(f, 1) : line 1 appears to contain an embedded nul
2: In readLines(f, 1) : line 1 appears to contain an embedded nul
My system is OS Windows 10. R version 4.1.3. R studio.
3 samples with missed clones and 3 normal samples are in attachement. As well as my script file.
I will be grateful for advice.
Thank you!
[Ba-L-05.txt](https://github.com/immunomind/immunarch/files/8411427/Ba-L-05.txt)
[BaLBa-07.txt](https://github.com/immunomind/immunarch/files/8411428/BaLBa-07.txt)
[BaLBl-09.txt](https://github.com/immunomind/immunarch/files/8411429/BaLBl-09.txt)
[int-06.txt](https://github.com/immunomind/immunarch/files/8411431/int-06.txt)
[trans-03.txt](https://github.com/immunomind/immunarch/files/8411432/trans-03.txt)
[VacBl-01.txt](https://github.com/immunomind/immunarch/files/8411433/VacBl-01.txt)
[Script.txt](https://github.com/immunomind/immunarch/files/8411452/Script.txt)

**Comment by Valeriy-Tereshchenko** [comment]
Hi, Aleksandr!
Proposed solution is useful.
I actually can add missed clones manually.
Thank you for your help!

**Comment by Alexander230** [comment]
I'm glad to hear that the problem is resolved. Feel free to reopen the issue if you have more questions.

Best regards,
Aleksandr

**Comment by anabbi** [comment]
Hi,

I am facing the same issue with MIXCR input files. Those files with one clone is loaded as empty. Is this fixed in the recent release?

Thanks

**Comment by Valeriy-Tereshchenko** [comment]
Hi, anabbi!
In my case, I had noticed that all removed sequencies were non-coding (nucleotide count is not a multiple of 3).  May be built-in algorithms.
You can check it.

**Comment by anabbi** [comment]
Okay. I see it now. 

Does `repLoad` always remove non-coding? If so, I think it would affect a command like this (from tutorial): `repFilter(immdata, .method = "by.clonotype", .query = list(CDR3.aa = exclude("partial", "out_of_frame")))$meta`

**Comment by Valeriy-Tereshchenko** [comment]
In my case,
repFilter(immdata, .method = "by.clonotype", .query = list(CDR3.aa = exclude("partial", "out_of_frame")))$meta
removed some additional non-coding clonotypes.
