### ISSUE TITLE
Support for file format Qiagen Immune Repertoire Analysis

### ISSUE THREAD

**Issue by ElviMagda** [immunomind/immunarch#232]
Dear Immunarch team,

We started to use the QIAseq Immune Repertoire kit from Qiagen for our bulk TCR sequencing. For the data processing, we used the module of the Qiagen CLC workbench. The output table looks like this:

![image](https://user-images.githubusercontent.com/58399552/166650415-36d78156-b1f2-4a39-bacc-3dfb6e635492.png)
https://resources.qiagenbioinformatics.com/manuals/biomedicalgenomicsanalysis/current/index.php?manual=Immune_Repertoire_Analysis.html

I would like to analyse the data with your very nice package :) Is there a possibility to implement this file format, please? 
Thanks in advance!

Best,
Elvira

**Comment by ElviMagda** [comment]
Hi,

we were able to export the data in the VDJ tool format with the CLC workbench and use it in the Immunarch package. So I think there is no need to implement the other format :)

Thanks anyway!
Best,
Elvira

**Comment by Alexander230** [comment]
Hi, Elvira!

I'm glad to hear that you've resolved the problem. Thank you for the instructions how to load the data from QIAseq to Immunarch!

Best regards,
Aleksandr Popov
