### ISSUE TITLE
bunch_translate error

### ISSUE THREAD

**Issue by gt7901b** [immunomind/immunarch#235]
## To Reproduce

1. bunch_translate('TGCGCTGTCCTCCCTGATGGCCAGAAGCTGCTCTTTGCAAGGGGGACCATGTTAAAGGTGGATCTTA')
2.
3.

when running this code to translate CDR3 sequence, bunch_translate('TGCGCTGTCCTCCCTGATGGCCAGAAGCTGCTCTTTGCAAGGGGGACCATGTTAAAGGTGGATCTTA')
output is 'CAVLPDGQKLLF~LQGGPC*RWIL'. This is wrong translation, should be CAVLPDGQKLLFARGTMLKVDL please check the bunch_translate code. The translation is correct until it got to GCA which should be translated to A, not ~

**Comment by Alexander230** [comment]
Hi, @gt7901b!

I'm Aleksandr Popov, a developer of Immunarch package. Thank you for using our software!

bunch_translate() function translates from both ends by default, and the length of your nucleotide sequence is 67, it's not a multiple of 3. To translate from the left side, use `.two.way = FALSE` argument:

```
> bunch_translate('TGCGCTGTCCTCCCTGATGGCCAGAAGCTGCTCTTTGCAAGGGGGACCATGTTAAAGGTGGATCTTA', .two.way = FALSE)
[1] "CAVLPDGQKLLFARGTMLKVDL"
```

Best regards,
Aleksandr
