### ISSUE TITLE
Integrate with seurat data

### ISSUE THREAD

**Issue by fredust** [immunomind/immunarch#266]
## ❓ Questions and Help
We have a set of [listed tutorials available on the website](https://immunarch.com/articles/).

Hello, thank you for designing this great package.
I have a question while analyzing the data with immunarch.

The classical seurat pipeline always includes the quality control step and might delete some low-quality cells. Should I also delete these cells in the filtered_contig_annotations.csv file and then run the `repLoad` to make the results more consistent?

Thank you very much.

**Comment by MVolobueva** [comment]
Hi, @fredust!

Thank you for using our package!

> Should I also delete these cells in the filtered_contig_annotations.csv file and then run the repLoad to make the results more consistent?

Yes, you should. Now there is no quality control step  in Immunarch for single-cell data. But we are currently working on it!

Best regards,
Maria Samokhina
