### ISSUE TITLE
Problems with metadata upload

### ISSUE THREAD

**Issue by annecar** [immunomind/immunarch#27]
Hi 
i have been trying for a long time now to import metadata with my data. 
the data is read fine, but the metadata not. I always get the following error: 

[metadata.txt](https://github.com/immunomind/immunarch/files/3789026/metadata.txt)
 ”[!] Samples found in the dataset, but not in the metadata: 18_5 22_5 24_5 Did you add all the necessary samples to the metadata file with correct names?”

Please find attached the metadata that was parsed using the following command, toghether with the files 18_5, 22_5, 24_5: 

immdata = repLoad("/Users/anner/AnneDoc/Results_2019/TCRa_Sequencing/Piotr_sequencing /bfx1062/files_grouped_forTcR/Group2_Teff")

Could you please have a look and let me know what is wrong? 

Thanks a lot !!!
annecar

**Comment by vadimnazarov** [comment]
Hi, thank you, we will look into it! We will have a new release at the beginning of the next week, so it should be fixed there. However, if you want to speed up things, can you please remove quotes `"` from the sample names, and try again?

**Comment by annecar** [comment]
Hi vadim! Thanks, For your quick answer. I am sorry to bother you... I will try again, though I am not aware of the quotes. Otherwise I will wait for the new release! Best Anne

On 31. Oct 2019, at 10:01, Vadim Nazarov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thank you, we will look into it! We will have a new release at the beginning of the next week, so it should be fixed there. However, if you want to speed up things, can you please remove quotes " from the sample names, and try again?

**Comment by annecar** [comment]
Hi, i had tried without before and it did not work either. 

thanks for your help 

Anne

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by vadimnazarov** [comment]
Hi, thank you, it should be fixed in todays release, we will message you here or by email when its ready!

**Comment by annecar** [comment]
Hi Vadim 
one more question: do you plan to ingrate the Shannon diversity index in your pipeline? 
That would be quite good. 
Thanks!! 
Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by vadimnazarov** [comment]
Can you provide a link to it please? Wikipedia, a publication, anything you find useful.

P.S. Todays release postponed to the middle of the week, sorry for that!

**Comment by annecar** [comment]
Dear Vadim 
for example used in this paper, there is also the original reference. 

ok, i wait to see the release… 

Something else: 
about IMMREP20: we should talk about a workshop or tool demo, as you said you would be interested to do some. Would you like to think about this and then i could arrange a call wit the other organisers? 

Thanks for all! 

Anne 



CRTD 

Anne Eugster, PhD
Head Single Cell Unit/
Scientist AG Bonifacio

Technische Universität Dresden
DFG-Center for Regenerative Therapies Dresden
Cluster of Excellence
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de 
Webpage: www.crt-dresden.de

**Comment by EugeneRumynskiy** [comment]
Hi @annecar 
We fixed the metadata problem in 0.5.2 version.
1. Update your package to 0.5.2. Get the latest version from master branch.
   - https://github.com/immunomind/immunarch/blob/master/immunarch.tar.gz
2. Just apply repLoad(...) to your **data folder** again and it will load the metadata file.
tmp = repLoad("path/to/your/data")
tmp$meta
names(tmp$data)
![image](https://user-images.githubusercontent.com/20778038/69238622-7ba4d500-0ba9-11ea-89a3-4692732d883e.png)
Hope we solved your problem :)

@vadimnazarov Will mail you about IMMREP20 and rarefaction in one of the next days.

**Comment by annecar** [comment]
Thanks a lot, Eugene!
I will give it a try asap.
@Vadim: talks for getting back to me, that would be great.

Best
Anne



Anne Eugster, PhD
Scientist AG Bonifacio

CRTD - Center for Regenerative Therapies TU Dresden
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de<mailto:a.eugster@crt-dresden.de>
Webpage: www.crt-dresden.de<http://www.crt-dresden.de>




On 20. Nov 2019, at 13:26, Eugene Rumynskiy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @annecar<https://github.com/annecar>
We fixed the metadata problem in 0.5.2 version.

  1.  Update your package to 0.5.2. Get the latest version from master branch.
     *   https://github.com/immunomind/immunarch/blob/master/immunarch.tar.gz
  2.  Just apply repLoad(...) to your data folder again and it will load the metadata file.
tmp = repLoad("path/to/your/data")
tmp$meta
names(tmp$data)
[image]<https://user-images.githubusercontent.com/20778038/69238622-7ba4d500-0ba9-11ea-89a3-4692732d883e.png>
Hope we solved your problem :)

@vadimnazarov<https://github.com/vadimnazarov> Will mail you about IMMREP20 and rarefaction in one of the next days.

**Comment by annecar** [comment]
Dear Eugene
the Metadata import worked perfectly! Thanks again.
Another thing: i tried to install 0.5.2 via CRAN as suggested on GitHub, but i get a teh waring :  in install.packages :
  package ‘immunarch’ is not available (for R version 3.6.1)
So i installed it as you suggested.
May be you would like to check back what is happening there.


Best
Anne


Anne Eugster, PhD
Scientist AG Bonifacio

CRTD - Center for Regenerative Therapies TU Dresden
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de<mailto:a.eugster@crt-dresden.de>
Webpage: www.crt-dresden.de<http://www.crt-dresden.de>




On 20. Nov 2019, at 13:26, Eugene Rumynskiy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @annecar<https://github.com/annecar>
We fixed the metadata problem in 0.5.2 version.

  1.  Update your package to 0.5.2. Get the latest version from master branch.
     *   https://github.com/immunomind/immunarch/blob/master/immunarch.tar.gz
  2.  Just apply repLoad(...) to your data folder again and it will load the metadata file.
tmp = repLoad("path/to/your/data")
tmp$meta
names(tmp$data)
[image]<https://user-images.githubusercontent.com/20778038/69238622-7ba4d500-0ba9-11ea-89a3-4692732d883e.png>
Hope we solved your problem :)

@vadimnazarov<https://github.com/vadimnazarov> Will mail you about IMMREP20 and rarefaction in one of the next days.

**Comment by annecar** [comment]
Hi !
Happy new year to the crew!
I have a question regarding downsampling:
how can i get “data’ attached to my downsampled batch?
when i downsample now, using
dsP1 = repSample(immdata$data, "downsample")
I do not have a $data slot.

Thanks a lot for your help!

Anne




Anne Eugster, PhD
Scientist AG Bonifacio

CRTD - Center for Regenerative Therapies TU Dresden
Fetscherstr. 105
01307 Dresden

Tel: +49 (0)351-458-821 41
Fax: +49 (0)351-458-821 09
Email: a.eugster@crt-dresden.de<mailto:a.eugster@crt-dresden.de>
Webpage: www.crt-dresden.de<http://www.crt-dresden.de>




On 4. Dec 2019, at 14:56, Vadim Nazarov <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #27<https://github.com/immunomind/immunarch/issues/27>.
