### ISSUE TITLE
fixVis : Error in if (is.na(.plot)) { : the condition has length > 1

### ISSUE THREAD

**Issue by Valeriy-Tereshchenko** [immunomind/immunarch#274]
## ❓ Questions and Help
We have a set of [listed tutorials available on the website](https://immunarch.com/articles/).
Dear colleagues,
When I apply fixVis() to any of my plots ( after vis() function) the error appears: fixVis : Error in if (is.na(.plot)) { : the condition has length > 1.  fixVis without arguments is calling diamonds dataset.
My system:
R 4.2.1 
ggplot2 3.3.6
immunarch 0.6.9
Rtools 4.2.0

Script example: 
#Overlap
repOverlap(InVitroList, .method = "morisita", .verbose = F) %>%
  vis("heatmap2") %>% 
  fixVis()

repOverlap(InVitroList, .method = "overlap", .verbose = F) %>%
  repOverlapAnalysis("mds") %>% 
  vis() %>% 
  fixVis()

#GeneUsage
geneUsage(InVitroList, "musmus.trbv", .norm = T) %>% 
  geneUsageAnalysis(.method = "js", .verbose = F) %>% 
  vis() %>% 
  fixVis()

How can I fix it?
Thank you!

**Comment by Alexander230** [comment]
Hello, Valeriy! I'm Aleksandr, a developer of Immunarch package. Thank you for using our software!

I've made a hotfix for this bug; you can try it by installing Immunarch from `dev` branch:

```
install.packages(c("devtools", "pkgload"))
devtools::install_github("immunomind/immunarch", ref="dev")
devtools::reload(pkgload::inst("immunarch"))
```

If you have more questions, feel free to ask them!

Best regards,
Aleksandr

**Comment by Valeriy-Tereshchenko** [comment]
Hello, Alexander!
The solution is working!
![fixVis_is_OK_png](https://user-images.githubusercontent.com/102950325/185620235-010ea5c9-acb9-4f0a-ad00-d0e2216ca030.png)
Thank you!

**Comment by Alexander230** [comment]
I'm glad to hear that it's working! If you have more questions, feel free to reopen the issue.
