### ISSUE TITLE
RepOverlapAnalysis Function Error

### ISSUE THREAD

**Issue by dimitrisokolowskei** [immunomind/immunarch#279]
Hello immunarch team,

I am facing the following error when using RepOverlapAnalysis() function:
```sh
Error in MASS::isoMDS(.data, k = 2, trace = FALSE) : 
  zero or negative distance between objects 1 and 3
```
I don't know if there's some trouble with my data or if it is a package bug. The code I'm using follows:
```sh
 repOverlapAnalysis(imm_ov1, "mds") %>% vis()
```
Basically, I am following the immunarch github tutorial. I would appreciate some help on this one. Thank you.

**Comment by MVolobueva** [comment]
Hi @dimitrisokolowskei !

I'm Maria Samokhina, a developer of Immunarch package. Thank you for using our software!

I've tried to reproduce the issue with built-in immdata, but this command worked without errors. So this can be an issue either with Immunarch installation, or with dataset. The things you can do to fix the issue or find out what's happening:

1. Run 'R --vanilla' in command line, install the latest version of Immunarch in that environment (install.packages("immunarch")) and try to repeat the command.
2. If you use your own data, try with built-in Immunarch data: data(immdata), then repeat the command.
3. If the issue happens with your data, but doesn't happen with Immunarch built-in data, try to do it with smaller subsets of your data. If you can attach a small reproducible example of data for which the error appears, it will help me to fix the issue.

Enjoy your week,
Maria

**Comment by dimitrisokolowskei** [comment]
Hello Maria,

Thank you very much for your response. I suppose the problem is with my dataset, since the error still persists, besides the multiples test that I made using the tips you gave. Anyway, thank you once again. 

All the best,
 Dimitri
