### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rgorsruch** [immunomind/immunarch#3]
After running the following code from documentation:

`> devtools::install_local("C:/immunarch/immunarch.tar.gz", dependencies = T)`

I'm receiving the following error:

Skipping 1 packages not available: MonetDBLite
Installing 40 packages: airr, circlize, config, cowplot, dbplyr, dendextend, diptest, dtplyr, ellipse, factoextra, FactoMineR, fastcluster, flashClust, flexmix, forge, fpc, generics, ggpubr, ggrepel, ggsci, ggsignif, GlobalOptions, gridBase, heatmap3, kernlab, leaps, mclust, modeltools, MonetDBLite, polynom, prabclus, r2d3, Rtsne, scatterplot3d, shape, shinythemes, sparklyr, treemap, trimcluster, viridis
Installing packages into ‘C:/Users/rgorsuch/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘MonetDBLite’ is not available (for R version 3.5.1)

immunarch is not showing up in my Packages library and the repLoad function is not present when trying to import data.

Thanks to anyone who can provide some insight!

Ryne

**Comment by vadimnazarov** [comment]
Hi, sorry for that, MonetDBLite was removed from the CRAN causing all this issues. We will publish the new version right now without this issue.

**Comment by vadimnazarov** [comment]
Published, please re-install `immunarch`

**Comment by vadimnazarov** [comment]
Hi, I will close this issue for now, please feel free to re-open if any questions arise.

**Comment by MaraLlamas** [comment]
Hi!
I have downloaded the 0.3.1 version and tried to install it. After running: <devtools::install_local("immunarch.tar.gz", dependencies=T)> 
(I have previously set the directory that contains immunarch as the working directory)

I get a very similar error:
Skipping 1 packages not available: MonetDBLite
Installing 95 packages: abind, airr, BH, car, carData, cellranger, circlize, colorspace, config, cowplot, crosstalk, data.table, DBI, dbplyr, dendextend, DEoptimR, diptest, dplyr, dtplyr, ellipse, ellipsis, factoextra, FactoMineR, fastcluster, flashClust, flexmix, forcats, forge, fpc, generics, ggplot2, ggpubr, ggrepel, ggsci, ggsignif, GlobalOptions, gridBase, gridExtra, gtable, haven, heatmap3, hexbin, hms, htmlwidgets, httpuv, kernlab, labeling, later, leaps, lme4, maptools, MatrixModels, mclust, minqa, modeltools, MonetDBLite, munsell, mvtnorm, nloptr, openxlsx, pbkrtest, plogr, plotly, plyr, polynom, prabclus, progress, promises, quantreg, r2d3, RColorBrewer, RcppEigen, readr, readxl, reshape2, rio, robustbase, Rtsne, scales, scatterplot3d, shape, shiny, shinythemes, sourcetools, sp, sparklyr, SparseM, tidyr, tidyselect, treemap, trimcluster, viridis, viridisLite, xtable, zip
Error: (converted from warning) package ‘MonetDBLite’ is not available (for R version 3.6.0)

I appreciate your kind help!
Mara

**Comment by vadimnazarov** [comment]
Hi, sorry for that, updated the package to 0.3.2 and fully removed MonetDBLite, should work now!

**Comment by MaraLlamas** [comment]
I could install it now
Thank you very much!

**Comment by vadimnazarov** [comment]
Glad to hear that!
