### ISSUE TITLE
repLoad error with 10x (fails to read bam.bai) 

### ISSUE THREAD

**Issue by flde** [immunomind/immunarch#311]
Hello Immunarch-team, 

many thanks for the great tool and documentation. I try to import 10x T-cell receptor sequencing data but repLoad fails when trying to read the all_contig.bam.bai file with `Error in tolower(l): invalid multibyte string 1`. 

Edit: When I use another 10x directory repLoad actually ignores the all_contig.bam.bai but raises an error when trying to read the concat_ref.bam.bai file. And other directories are actually correctly imported. But all 10x directories are of the same structure and from the same patient, just different time points. 

Any help is highly appreciated! 

Best wishes, 
Florian

**Comment by flde** [comment]
Would I loose any functionality of the immunarch universe if I just import the filtered_contig_annotations.csv file of my samples manually? I manged to do so and just create the immdata object list myself wich seems to work for some applications so far. 

Many thanks

**Comment by Alexander230** [comment]
Hi, Florian!

I'm Aleksandr Popov, a developer of Immunarch package. Thank you for using our software!

Can you, please, send example files that trigger parsing errors? It will help me to fix the parser. Yes, you can create immdata objects yourself without losing any functionality. You can load an example object with `data(immdata)` command and look inside to check its format, then recreate the same structure with your data.

Best regards,
Aleksandr

**Comment by royfrancis** [comment]
I get the same error. The strange thing is that for some of the `.bai` files, I get

`unsupported format, skipping`,

but some other `.bai` files, I get `Error in tolower(l) : invalid multibyte string 1`.

Are the `.bai` index files actually used? Just wondering why it's being read in the first place.

I moved the `.bai` files outside the path and this error goes away.

**Comment by flde** [comment]
Hi, 

sorry for my late reply and many thanks for your help @Alexander230!. @royfrancis I lost track of what is happening but it worked for me as described above. 

Best wishes, 
Florian
