### ISSUE TITLE
Adjust barcodes for select_barcodes and select_clusters with multiple samples 

### ISSUE THREAD

**Issue by flde** [immunomind/immunarch#314]
Dear Immunarch Team, 

I have multiple patient and time point samples (10x) which TCR repertoir I want to compare. For each sample I want to do splits by genotype, HTO etc. and therefore want to use the select_ functions. 

However, the Seurat cell barcodes are adjuted by adding a sample suffix while the TCR 10x data are still annotated with the orginal barcode. So I guess the select_ functions do not work? 

I can adjust the 10x data manually but I would like to ask if you have an solution implemented already. 

Best, 
Florian

**Comment by Alexander230** [comment]
Hello, Florian!

I'm Aleksandr Popov, a developer of Immunarch package. Thank you for using our software!

Currently, Single Cell support is in beta in Immunarch, so there are some things not implemented or contain bugs. We plan to work on Single Cell support improvement in the next version of Immunarch.

If you can attach an example of your data, I can help with tweaking and modifying it to make it load in Immunarch correctly.

Best regards,
Aleksandr

**Comment by flde** [comment]
Hello @Alexander230, 

Many thanks for your help. I wrote some wrapper functions which does the trick for now. 

Best wishes, 
Florian
