### ISSUE TITLE
Error with installing and loading IMGT output

### ISSUE THREAD

**Issue by Tjitskedv** [immunomind/immunarch#33]
Hi, 

I’m trying to install immunarch in R with: 
> install.packages("immunarch")

But I get the following error: 
Warning message:
package ‘immunarch’ is not available (for R version 3.6.1) 

I also tried installing it in R version 3.2.3 and it gave the same error. 

Because this didn’t work I installed the pre-release version and tried to load IMGT output data. But then I also get an error: 
> install.packages("devtools")
> devtools::install_url("https://github.com/immunomind/immunarch/raw/master/immunarch.tar.gz")
> imgtdata=repLoad("path_to_file", .format="imgt")
== Step 1/3: loading repertoire files... ==
Processing "path_to_file" ...
  -- Parsing "path_to_file/1_Summary.txt" -- imgt
Warning: 2 parsing failures.
row col   expected    actual                                                                          file
  1  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
  1  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'

Warning: 12330 parsing failures.
row col   expected    actual                                                                          file
  1  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
  2  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
  3  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
  4  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
  5  -- 34 columns 4 columns 'path_to_file/1_Summary.txt'
... ... .......... ......... .............................................................................
See problems(...) for more details.

Error in if (any(str_detect(.name[i], c("TCRA", "TRAV", "TCRG", "TRGV",  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: Missing column names filled in: 'X34' [34] 
2: Missing column names filled in: 'X34' [34]

**Comment by vadimnazarov** [comment]
Hi @Tjitskedv 

thank you for using our package! 

Regarding CRAN: immunarch is not yet on CRAN, so the correct way to install it is indeed via devtools.

Regarding the repLoad issue. Can you please send us at support@immunomind.io a sample of your data so we can test it and fix it?

**Comment by EugeneRumynskiy** [comment]
The issue was solved.

**Comment by EugeneRumynskiy** [comment]
@Tjitskedv ping. How it's going? Have you managed to install the last version of the package? Is there any other troubles you have?

**Comment by vadimnazarov** [comment]
@Tjitskedv ping

**Comment by vadimnazarov** [comment]
Sadly, we didn't manage to reproduce the issue. Please feel free to re-open this issue in case of a similar problem and send us a sample of your file to support@immunomind.io
