### ISSUE TITLE
Visualisation issues (vis)

### ISSUE THREAD

**Issue by GBeattie** [immunomind/immunarch#35]
## 🐛 Bug
Attempts to visualise several analysis either result in warning messages with no output, or just no output. I'm guessing it may be due to the structure of my data so I'll include my repLoad procedure below.

## To Reproduce
1. Data is the filtered annotation files for two 10x samples. Samples seemed to read in ok, although got warning message (The following named parsers don't match the column names: barcode...). Read in using: 

`immdata <- repLoad("./immunarch")`

metadata.txt content:

Sample
wt_UT
wt_aCT

2. Example of vis command with warning and no output:

```
> exp_vol = repExplore(immdata$data, .method = "volume")
> vis(exp_vol, .by = c("Sample"), .meta = immdata$meta)
Warning: Ignoring unknown aesthetics: y
Warning: Ignoring unknown aesthetics: xmin, xmax, annotations, y_position
```

3. Example of vis command with no output (or warning):

```
> exp_len = repExplore(immdata$data, .method = "len", .col = "aa")
> vis(exp_len)
```

## Expected behavior

Graphical output of data

## Additional comments

Several other vis inputs result in the same issue, happy to list them if that's of use, also happy to provide sample dataset. Suspicion the issue may lie in the "Source" section of the metadata, which is just my sample names in triplicate (see below), which may be confuse vis.

```
> immdata[["meta"]][["Source"]]
[1] "wt_aCT" "wt_aCT" "wt_aCT" "wt_UT"  "wt_UT"  "wt_UT" 
```

**Comment by vadimnazarov** [comment]
Hi @GBeattie ,

thank you for letting us know about the issue and following the bug template! We will fix it in the next release before New Years Eve. As a workaround, you can use `plot`:

```
exp_len = repExplore(immdata$data, .method = "len", .col = "aa")
plot(vis(exp_len))
```

**Comment by GBeattie** [comment]
@vadimnazarov 

Thanks for the workaround, working with the other cases where plots weren't appearing also.
