### ISSUE TITLE
repLoad question: Warning: found NAs in clonal counts. Setting them to 1's.

### ISSUE THREAD

**Issue by JHYSiu** [immunomind/immunarch#362]
I am unable to calculate clones when loading AIRR data. The data is 10x TCR [data](url) that I have QC'd and saved as AIRR file (see sample attached) for loading. 

Code used: 
combined_immdata <- repLoad(file_path, .mode = "paired")

What columns of data are being used to calculate the clones? 
[test_TCR_airr.csv](https://github.com/immunomind/immunarch/files/11576801/test_TCR_airr.csv)

Thanks!

**Comment by zelenkt** [comment]
The same problem occurs when using AIRR data generated by TRUST4 (from bulk RNA-seq). I assume the problem is caused by the fact that the TRUST4 report contains consensus_count whereas Immunarch expects only duplicate_count.

**Comment by JHYSiu** [comment]
thanks! replaced my umi_count column with duplicate_count, and it works.
