### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jcs3632** [immunomind/immunarch#37]
Hello,

I'm getting an error when installing the package using:
```
devtools::install_url("https://github.com/immunomind/immunarch/raw/master/immunarch.tar.gz")
```
Here's the error:
```
Error: (converted from warning) package 'dtplyr' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'immunarch'
Error: Failed to install 'unknown package' from URL:
(converted from warning) installation of package ‘C:/Users/X/AppData/Local/Temp/RtmpQ1Pgsx/file3b747cab2090/immunarch_0.5.4.tar.gz’ had non-zero exit status
```
I also tried installing it locally and get the same message. How can I fix this?

Thanks

**Comment by EugeneRumynskiy** [comment]
Hello @jcs3632 ! I've passed this issue to developer, it looks like we have a version conflict. I hope we will update this issue tomorrow with a suitable answer.

**Comment by EugeneRumynskiy** [comment]
Dear @jcs3632! There is a quick fix for the problem in the docs. Please go to [Installation troubleshooting section](https://immunarch.com/articles/v1_introduction.html#installation-troubleshooting) and look at the subsection number 9.

If you have error messages like the following (note the (converted from warning) part):
`byte-compile and prepare package for lazy loading`
`Error: (converted from warning) package 'ggplot2' was built under R version 3.6.1`
`Execution halted`
`ERROR: lazy loading failed for package 'immunarch'`

Execute the following command in R and try again to install the package:

Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")

**Comment by peter-yufan-zeng** [comment]
@EugeneRumynskiy  I was running into the same problem. Your work around fixed the issue for me! Thanks a bunch!!! :)

**Comment by vadimnazarov** [comment]
@jcs3632 it seems that the issue can be easily fixed. Feel free to try the solution above and re-open the issue in case it didn't work.
