### ISSUE TITLE
Adding a new proportions scale or consistent scale for  multiple samples 

### ISSUE THREAD

**Issue by apal6** [immunomind/immunarch#384]
Hi,

Thank you for the wonderful package. 

I have four samples and I want to have two y-axis scales for two conditions. I was trying to edit the function `vis.immunr_dynamics`
but there are multiple errors. Is there a better way to add two proportions axis on the alluvial plot? 

Thank you in advance.

**Comment by vadimnazarov** [comment]
Hi @apal6 

Thank you for using the package! Could you share an example of a plot with two y-axes? I'm not totally sure that I understood your idea. Something like this? 

![image](https://github.com/immunomind/immunarch/assets/2979713/4ce21cd1-f681-4bc8-91a0-e35dda8cb2f8)

If so, I'm not sure how to do it. I'm not sure if ggalluvial allows this at all. Is there a reason for two plots side-by-side not working for you?

**Comment by apal6** [comment]
Thank you for prompt response @vadimnazarov . Yes, this is essentially what I want: 
Sample data:
```
tc1
       CDR3.aa     conditionA-1           conditionA-2           conditionB-1              conditionB-2
 1:     X               0.0003776435     0.0000000000        0.0000000000          0.0000000000
 2:     Y               0.0004855416     0.0012249898         0.0006634379         0.0005046682
```

Since the range of proportions in condition A and B varies alot, I thought of plotting them with two seperate axes to see the stacks of clonotypes regardless of how small the proportion is. 

Like in the plot below, the scale helps in visualizing the MS1 sample only, if I could have a smaller scale on the right side to also accommodate lower proportion values to visualize other samples as well. 

![Screenshot 2023-11-02 at 11 10 59 AM](https://github.com/immunomind/immunarch/assets/127814354/12b8b3d1-1011-4357-8cfe-3b28798d3732)

Thank you so much!

**Comment by apal6** [comment]
<img width="898" alt="Screenshot 2023-11-02 at 12 53 09 PM" src="https://github.com/immunomind/immunarch/assets/127814354/d1edaa52-f7a3-4217-bc5a-7fdf90394efc">
 
I tried editing the main function but couldn't get the alluvial plot. If you see the Y axes scales, they vary alot. Appreciate your help!
