### ISSUE TITLE
Can't upload immunarch formated table.

### ISSUE THREAD

**Issue by tiagobrc** [immunomind/immunarch#39]
## 🐛 Bug

immunarch formated files are not being imported

## To Reproduce

1.`immdata = repLoad(.path = "AF.tsv", .format = 'immunarch')`
2.
3.

```
Error in `[[<-.data.frame`(`*tmp*`, IMMCOL$cdr3nt, value = logical(0)) : 
  replacement has 0 rows, data has 3
```

[AF.tsv.zip](https://github.com/immunomind/immunarch/files/4099149/AF.tsv.zip)

## Expected behavior

I should be able to import it into an immdata object

**Comment by EugeneRumynskiy** [comment]
Hello @tiagobrc! We reproduced the issue, thank you for noting us. I hope we'll resolve it by the end of the week.

**Comment by vadimnazarov** [comment]
Hi @tiagobrc !

We published immunarch on CRAN and moved it to GitHub, feel free to install the latest versions and check if everything is OK. I'm closing this issue for now, please feel free to reopen it in case of more related questions.
