### ISSUE TITLE
Trouble loading an entire directory

### ISSUE THREAD

**Issue by ssudhaman** [immunomind/immunarch#4]
Hi,
When I use repLoad(/path/to/mixcrclonesoutputfile.txt), I can do so without any problems.

However, when I use repLoad(/path/to/foldercontainingseveralmixcrclones.txtfiles/), I get this error-
Error in strsplit(df[[.dalignments]], "|", T, F, T) : 
  non-character argument

The folder contains a metadata.txt file with 3 tab-separated columns:
Sample Column1 Column2

Wondering if anyone knows what the issue seems to be?
Thanks.

**Comment by vadimnazarov** [comment]
Hi,

Can you please identify what exact file causes the fail? For example, you can make a directory with only one file and a metadata file with this file, and check if repLoad works.

Alternatively, you can send me an archive with the folder with the metadata file and MiXCR files with the first 3-5 lines from each of them so I can test it on my side. Send it to vdm.nazarov at gmail.com

It seems that the issue with the parsing, so we will add new parser, and everything will work after that.

**Comment by vadimnazarov** [comment]
Fixed in the 0.3.2 version.
