### ISSUE TITLE
MiXCR import no longer works

### ISSUE THREAD

**Issue by MikolajKocikowski** [immunomind/immunarch#401]
## 🐛 Bug

Hi, I keep getting an error trying to load any MiXCR output to Immunarch. The message "Samples found in the metadata, but not in the folder" is not helpful, but the issue I think is that Immunarch requires the clones.txt files from MiXCR, but MiXCR outputs clones.tsv files now, which differ in content and are not recognized. Is exporting-importing airr fles the recommended solution now, or is there another way to make these compatible? Thanks

**Comment by MikolajKocikowski** [comment]
Okay, I figured Immunarch can import the newer clones.tsv files from MiXCR output too, but - just as with AIRR files - will recognize them or not depending on the file names (rules unclear). I will enquire with Immunarch, and MiXCR is not really involved in the problem, hence solved.

**Comment by MikolajKocikowski** [comment]
The issue is on the Immunarch side, not MiXCR.

**Comment by vadimnazarov** [comment]
Hi, could you try to export MiXCR files in the AIRR format please? We are working on the next version of Immunarch, and consider dropping the support for non-AIRR standard formats as they are too cumbersome to support.

**Comment by vadimnazarov** [comment]
(responded to you on Linkedin)

**Comment by MikolajKocikowski** [comment]
Hi, thanks for the reply and that's great news - looking forward to the next release! 

I apologize I forgot to close this issue - I finally figured out I can import new MiXCR files just as well as airr - but both only when the files have some specific names and not others... Opened another issue about this, co closing here.
