### ISSUE TITLE
File naming vs loading problems

### ISSUE THREAD

**Issue by MikolajKocikowski** [immunomind/immunarch#402]
## 🐛 Bug
Hi! 

The tutorial suggests various file types can be loaded, with various names, as long as the basename is in the metadata table. Meanwhile, I resorted to AIRR because MiXCR files seemed no longer compatible, and by trial and error I found that Immunarch only recognizes files under some names. For insance "barcode01.tsv" is "-- --" and causes errors, but the same file renamed "clones01.tsv" is "-- airr  --" and fine. Only now I only realized the MiXCR-generated tsv files become "-- mixcr --" too if I apply the same (problematic) naming scheme... What is going on?

**Comment by vadimnazarov** [comment]
Hi, "barcode" is a reserved word for the file with barcodes. Please use other file names.

**Comment by MikolajKocikowski** [comment]
Hi, I see! Any other forbidden words :)? Maybe that's just a my limited experience, but I did not expect this - especially that this is how our facility names files after demultiplexing, and the files originally had more coplex names with "barcode" in them. Could be helpful to include this in documentation, and I'm sorry if I missed this. In any case thank you for solving the mystery!
