### ISSUE TITLE
RepLoad issue with MiXCR files 

### ISSUE THREAD

**Issue by AnaBolivar** [immunomind/immunarch#41]
Hello, 
I just started using Immunarch today but when trying to parse a folder with different .txt clonoset files that I obtained using mixcr it gives me the following error

> TCRAs <- repLoad("Users/abolivar1/Documents/TCRseq Project/Bioinformatics/TCRAs/", .format = "mixcr")
== Step 1/3: loading repertoire files... ==
Error in if (file.info(path)$isdir) { : 
  missing value where TRUE/FALSE needed

I am not sure what would be wrong with the files, as I am using them straight from Mixcr.

Any help would be appreciated

Thanks, 
Ana

**Comment by clarapereira** [comment]
Hi!

I'm experiencing the same problem. I have no problems loading the data that comes with the package, but can't load my datasets, clonotype files obtained with mixcr:

`> immdata <- repLoad("../data/sample1_folder/sample1.clonotypes.TRA.txt", .format = "mixcr")
== Step 1/3: loading repertoire files... ==
Error in if (file.info(path)$isdir) { : 
  missing value where TRUE/FALSE needed
> `

`> immdata <- repLoad("../data/sample1_folder/sample1.vdjca", .format = "mixcr")
== Step 1/3: loading repertoire files... ==
Error in if (file.info(path)$isdir) { : 
  missing value where TRUE/FALSE needed
> `

I'd love to try out Immunarch, so any help with this problem would be much appreciated!

Best,
Clara

**Comment by hpessa** [comment]
I wonder if this is the same problem I have. When you load a directory, the error message is more detailed:

```
22 parsing failures.
 row               col           expected               actual
1838 allDHitsWithScore 1/0/T/F/TRUE/FALSE TRDD3*00(70)        
1838 allDAlignments    1/0/T/F/TRUE/FALSE 12|26|39|20|34||70.0
1840 allDHitsWithScore 1/0/T/F/TRUE/FALSE TRDD3*00(40)        
1840 allDAlignments    1/0/T/F/TRUE/FALSE 14|22|39|23|31||40.0
1842 allDHitsWithScore 1/0/T/F/TRUE/FALSE TRDD3*00(40)
```

It seems D alignments are not handled correctly. I am using mixcr v3.0.12 and immunarch v0.5.5. Are they not compatible?

**Comment by vadimnazarov** [comment]
@AnaBolivar @clarapereira @hpessa 

Hi, thank you for letting us know about the issue and sorry for the very late response! 

Can you please send us a small subset of your data to test? support@immunomind.io

MiXCR files are tricky to work with, and we would greatly appreciate your help here.

**Comment by vadimnazarov** [comment]
Issue update.

After email conversations with researchers who reported the issue, we fixed some of the parsing issues in the latest `immunarch` version. 

To ensure that you are parsing the repertoire files correctly, make sure to:
1. Apply the `repLoad` without (!) format specification, i.e., don't pass the `.format` argument. If `repLoad` doesn't work without the argument - it won't work at all.
2. Apply the `repLoad` to a folder with repertoire files. Singular files work too, but to make the analysis fast make sure to move all your repertoire files into the same folder and create a `metadata.txt` file with all the meta-information needed for the analysis. You can find more information here: https://immunarch.com/articles/v2_data.html
3. Apply the `repLoad` to the text / table files with clonotypes from MiXCR and other tools. `*.vdjca` and `*.report` files are suitable. We will make sure they are skipped in the next versions of `immunarch`. We already skipping `.fasta`, `.fastq` and other file formats which comes from single-cell sequencing.

Some of the reported issues were warnings, not errors. Even if you get a long message in your console, please check your data! We are working on removing obscure warning messages from the package to ensure the smooth experience.

I'm closing this issue for now, but please feel free to re-open it if the same problem persists. The whole ImmunoMind team sincerely appreciates you taking your time getting back to us and report this issues. @AnaBolivar , @clarapereira and @hpessa - thank you a lot!
