### ISSUE TITLE
rarefraction - seq default error

### ISSUE THREAD

**Issue by sravani9408** [immunomind/immunarch#44]
## rarefraction - seq.default error
Hello, 

When I try to run rarefraction on my data it returns the following error. Can you please help? 

imm_raref = repDiversity(mydata$data, "raref", .extrapolation = 200000, .verbose = F)
Error in seq.default(tail(seq(.step, sum(.data[[i]]), .step), 1) + .step,  : 
  wrong sign in 'by' argument

I am not sure if the error is because of huge datasets. 
mydata is a list of 3 dataframes. 
> dim(mydata[["data"]][["R_1"]])
[1] 143866     11
> dim(mydata[["data"]][["R_2"]])
[1] 823220     11
> dim(mydata[["data"]][["R_3"]])
[1] 980159     11

Thanks!

**Comment by vadimnazarov** [comment]
Hi @sravani9408 

thank you for letting us know about the bug. Sorry for the late response!

Can you please tell me what version of immunarch do you use? 

Does repDiversity fail on all three of data frames? Can you please run repDiversity separately on each one and see if it works on some?

Is it possible for you to send me a part of your data to test? Via support@immunomind.io

**Comment by jchenpku** [comment]
I came cross similar error and there will be no error without adding ".extrapolation = 200000".

**Comment by vadimnazarov** [comment]
Ping about the rarefaction issues @sravani9408

**Comment by vadimnazarov** [comment]
In the latest release we improved the diversity vignette to make sure people don't use the `.extrapolation` argument without a real need in it.

**Comment by sravani9408** [comment]
Hello @vadimnazarov,

Thank you so much for all the help. I did try running on individual data frames, but it still returns the same error. It works without extrapolation, I have attached the graph below(Is this normal). Also, I was wondering if there is a way to use extrapolation. And Sorry, I cannot share the data as it is not published. 

<img width="192" alt="Raref" src="https://user-images.githubusercontent.com/47796322/81707186-7597fe80-943e-11ea-9310-becb816dc75b.png">
?
Thanks again.

**Comment by sravani9408** [comment]
Hello @vadimnazarov,

Thank you so much for all the help. I did try running on individual data frames, but it still returns the same error. It works without extrapolation. Also, I was wondering if there is a way to use extrapolation. And Sorry, I cannot share the data as it is not published.

Thanks again.

**Comment by vadimnazarov** [comment]
Hello @sravani9408 

We will update the package soon, I will ping you and let's continue the conversation after that. We'll look into this issue!

**Comment by sravani9408** [comment]
Sounds good, thanks!

**Comment by vadimnazarov** [comment]
Hi @sravani9408 !

We published immunarch on CRAN and moved it to GitHub, feel free to install the latest versions and check if everything is OK. I will leave this issue open until you confirm that everything is OK.

**Comment by sravani9408** [comment]
Hello @vadimnazarov,

That works! thank you so much!!
Just a quick question,  I am running rarefaction on a huge dataset and the job is running for 8 days now.  Can we speed up rarefaction using multi-thread?  Thanks!

**Comment by vadimnazarov** [comment]
@sravani9408 

Wonderful, thank you! 

Yes, I see the issue here. Would you like to have 20 minute discussion about the issue and your pipelines over Zoom so we quickly discuss it in the details? Email us on support@immunomind.io and I will get back to you over the email so we can close this issue. Large-scale data is what we aim to, and there are different approaches and workarounds.

**Comment by sravani9408** [comment]
@vadimnazarov Sure, that would be really helpful! I will send an e-mail shortly. Thanks!

**Comment by Manikgarg** [comment]
I am getting the same error with immunarch version ‘0.6.5’ with or without using the .extrapolation argument.
