### ISSUE TITLE
Datatable error when dividing public repetoir

### ISSUE THREAD

**Issue by gustavjoh** [immunomind/immunarch#45]
Hi, I get the following error when running the code below that it is complaining about the syntax ":=". I'm using R 3.6.3 and Immunoarch 0.5.5 and dplyr 0.8.5 on a Windows 10. I assume it is some bug related to which version of packages you use...

```
library(immunarch)
data("immdata")
immdata <- immdata 

pr = pubRep(immdata$data, "aa", .coding = T, .verbose = F)
pr1 = pubRepFilter(pr, immdata$meta, c(Status = "C"))
pr2 = pubRepFilter(pr, immdata$meta, c(Status = "MS"))
pr3 = pubRepApply(pr1, pr2,) 
```

> Error in `:=`(Samples.y, NULL) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

I also get a warning when running pubRepFilter that:

> You are using a dplyr method on a raw data.table, which will call the data frame
> implementation, and is likely to be inefficient.
>
> To suppress this message, either generate a data.table translation with `lazy_dt()`
> or convert to a data frame or tibble with `as.data.frame()`/`as_tibble()`.You are using a dplyr method on a raw data.table, which will call the data frame implementation, and is likely to be inefficient.
>
> To suppress this message, either generate a data.table translation with `lazy_dt()`
> or convert to a data frame or tibble with `as.data.frame()`/`as_tibble()`.

**Comment by ahurbanski** [comment]
Hey @gustavjoh.

I was facing the same issue trying to use the pubRepApply function. This is how dealt with it:

I searched for the function code with` trace(pubRepApply, edit = T)` and copied it to my script with another name, but changing the original line

`    pr.res = dplyr::inner_join(.pr1, .pr2, by = col_before_samples)
`

for this

`  pr.res = as.data.table(dplyr::inner_join(.pr1, .pr2, by = col_before_samples))
`

as it follows:

```
my_function <- function (.pr1, .pr2, .fun = function(x) log10(x[1])/log10(x[2])) 
{
  col_before_samples = names(.pr1)[1:(match("Samples", colnames(.pr1)) - 
                                        1)]
  tmp = rowMeans(public_matrix(.pr1), na.rm = T)
  .pr1[, (match("Samples", colnames(.pr1)) + 1):ncol(.pr1)] = NULL
  .pr1[["Quant"]] = tmp
  tmp = rowMeans(public_matrix(.pr2), na.rm = T)
  .pr2[, (match("Samples", colnames(.pr2)) + 1):ncol(.pr2)] = NULL
  .pr2[["Quant"]] = tmp
  pr.res = as.data.table(dplyr::inner_join(.pr1, .pr2, by = col_before_samples))
  pr.res[["Samples.x"]] = pr.res[["Samples.x"]] + pr.res[["Samples.y"]]
  pr.res[, `:=`(Samples.y, NULL)]
  names(pr.res)[match("Samples.x", colnames(pr.res))] = "Samples"
  pr.res[["Result"]] = apply(pr.res[, c("Quant.x", "Quant.y")], 
                             1, .fun)
  add_class(pr.res, "immunr_public_repertoire_apply")
}

```

Then calling the new function:

`pr3 = my_function(pr1, pr2) 
`

I don't know how the output was intended to be, but I think it's working fine now.

Hope it helps.

**Comment by gustavjoh** [comment]
Thank you!

Your solution works, seems like the line causing the problem is the one below.

` pr.res[, `:=`(Samples.y, NULL)]`

What I can see is that it only removes the column "Samples.y" so that line could also be replaced by the code below, perhaps not as clean code. But at least it doesn't change the datatype.

'pr.res = dplyr::select(pr.res, -Samples.y)'

Hope this is fixed in the next version 

Thank you again!
