### ISSUE TITLE
The picture does not match the data

### ISSUE THREAD

**Issue by jeitziner** [immunomind/immunarch#46]
## 🐛 Bug
I think the .by argument in vis is not fully working at least when a vector is provided (Version : immunarch_0.3.3.9005)
## To Reproduce
This is what I get when looking at exp_vol
> exp_vol$Volume
[1]  213 5647 1333 2658  528 1326
> by_vec = factor(c("D","S","D","S","L","N"))
> by_vec
[1] D S D S L N
Levels: D L N S
> p = vis(exp_vol, .by = by_vec)
Warning: Ignoring unknown aesthetics: y
Warning: Ignoring unknown aesthetics: xmin, xmax, annotations, y_position
> p
<img width="846" alt="Capture d’écran 2020-04-08 à 15 01 53" src="https://user-images.githubusercontent.com/32093941/78786975-e8c6d480-79a9-11ea-8105-ac4daf476995.png">

## Expected behavior
As one can see first D value is 213 second D value is 1333 and not 5647 as in the picture. 

Thank you for your help!

**Comment by vadimnazarov** [comment]
Hi @jeitziner ,

sorry for the late response. Can you please update to the latest immunarch versions 0.5.5 and try again? It's a known bug and we fixed it in the post-0.3.3 version. Let's keep this issue open until you confirm that everything works correctly.

**Comment by jeitziner** [comment]
Solved, thank you !

Le dim. 12 avr. 2020 à 16:27, Vadim Nazarov <notifications@github.com> a
écrit :
