### ISSUE TITLE
repDiversity .method="dXX" not working

### ISSUE THREAD

**Issue by jmmontagne** [immunomind/immunarch#47]
## ❓ Questions and Help
The following code gives an error:
div_d10 = repDiversity(.data = coding(immdata$data), .method = "dXX", .perc = 10)
Error in FUN(X[[i]], ...) : 
  You entered the wrong method! Please, try again.

Thank you in advance for your assistance!

**Comment by jmmontagne** [comment]
I figured out that the repDiversity d50 method defines clonotypes by unique CDR3.aa rather than full nucleotide sequence, which was the default for the repClonality clonal.prop method.

However 
div_d10 = repDiversity(.data = coding(immdata$data), .method = "dXX", .perc = 10)
is still not working.

**Comment by vadimnazarov** [comment]
Hi @jmmontagne , try `.method = "dxx"`

**Comment by jmmontagne** [comment]
Easy fix- thank you!

**Comment by vadimnazarov** [comment]
My pleasure, and thank you for pointing me to this! A small issue, but irritating nonetheless. It will be fixed in the next release, as soon as we release the CRAN version.
