### ISSUE TITLE
Wrong formula for Jaccard index?

### ISSUE THREAD

**Issue by luciacsep** [immunomind/immunarch#48]
## 🐛 Bug
When using the `repOverlap` function using the Jaccard index, I think it calculates wrong numbers. When looking at the source code in `overlap.R`, I saw that the Jaccard index is calculated as follows:
```
jaccard_index.default <- function(.x, .y) {
  .x = collect(.x, n = Inf)
  .y = collect(.y, n = Inf)
  intersection = nrow(dplyr::intersect(.x, .y))
  intersection/(nrow(.x) + nrow(.y) + intersection)
}
```

However, doesn't the intersection need to be subtracted:
` intersection/(nrow(.x) + nrow(.y) - intersection)`
?

I'm using Immunarch v. `0.5.5`.

Thank you.

**Comment by vadimnazarov** [comment]
Hi @luciacsep ,

thank you a lot for noticing this critical issue! It will be fixed in the next release.

**Comment by vadimnazarov** [comment]
Hi @luciacsep !

Thank you again for noticing the bug, we published immunarch on CRAN and moved it to GitHub, feel free to install the latest versions and check if everything is OK for you. I'm closing this issue for now, please feel free to reopen it in case of more related questions.

**Comment by Nitin123-4** [comment]
Hi One confusion:

jaccard_index.default <- function(.x, .y) {
  .x <- collect(.x, n = Inf)
  .y <- collect(.y, n = Inf)
  intersection <- nrow(dplyr::intersect(.x, .y))
  intersection / (nrow(.x) + nrow(.y) - intersection)
}

Is it we need to make unique of .x and .Y and then nrow()?
