### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by joaorlj** [immunomind/immunarch#5]
Hi

After running the following code from documentation in Windows10:

install.packages("devtools", dependencies = T)
devtools::install_local("path/to/your/folder/with/immunarch.tar.gz", dependencies=T)

I'm receiving the following error:

The downloaded binary packages are in
        C:\Users\João Drama\AppData\Local\Temp\Rtmp8a5Pdw\downloaded_packages
  
  
  
   checking for file 'C:\Users\João Drama\AppData\Local\Temp\Rtmp8a5Pdw\remotes1bc85014173\immunarch/DESCRIPTION' ...
  
   checking for file 'C:\Users\João Drama\AppData\Local\Temp\Rtmp8a5Pdw\remotes1bc85014173\immunarch/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\João Drama\AppData\Local\Temp\Rtmp8a5Pdw\remotes1bc85014173\immunarch/DESCRIPTION' (1.9s)

  
  
  
-  preparing 'immunarch': (2.8s)
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information
-  cleaning src

  
  
  
   checking vignette meta-information ...
  
√  checking vignette meta-information

  
  
  
-  excluding invalid files (1.1s)

  
   Subdirectory 'inst/doc' contains invalid file names:
     '1_introduction.Rmd' '2_data.Rmd' '3_basic_analysis.Rmd'
     '4_overlap.Rmd' '5_gene_usage.Rmd' '6_diversity.Rmd' '7_fixvis.Rmd'
     '1_introduction.html' '2_data.html' '3_basic_analysis.html'
     '4_overlap.html' '5_gene_usage.html' '6_diversity.html'
     '7_fixvis.html'

  
Warning in .write_description(db, ldpath) :
  
   Warning in .write_description(db, ldpath) :
     Unknown encoding with non-ASCII data: converting to ASCII

  
  
  
-  checking for LF line-endings in source and make files and shell scripts

  
  
  
-  checking for empty or unneeded directories

  
  
  
-  looking to see if a 'data/datalist' file should be added

  
  
  
-  building 'immunarch_0.3.2.tar.gz'

  
   

Installing package into ‘C:/Users/João Drama/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'immunarch' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Joco Drama/Documents/R/win-library/3.5/immunarch/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  nÃ£o Ã© possÃ­vel abrir a conexÃ£o
ERROR: installing package DESCRIPTION failed for package 'immunarch'
* removing 'C:/Users/João Drama/Documents/R/win-library/3.5/immunarch'
In R CMD INSTALL
Error in i.p(...) : 
  (convertido do aviso) installation of package ‘C:/Users/JOODRA~1/AppData/Local/Temp/Rtmp8a5Pdw/file1bc81dbd528c/immunarch_0.3.2.tar.gz’ had non-zero exit status
> 
> 
> 
> l´
Erro: unexpected input in "l´"

Thanks to anyone who can provide some insight!

Joao

**Comment by vadimnazarov** [comment]
We contacted with Joao by email, but just for other users: check this thread: https://community.rstudio.com/t/help-regarding-package-installation-renviron-rprofile-r-libs-r-libs-site-and-r-libs-user-oh-my/13888/8
