### ISSUE TITLE
Gene usage visualisation grouped by metadata

### ISSUE THREAD

**Issue by MaraLlamas** [immunomind/immunarch#6]
Hi, 
I am trying to graph gene usage in samples as grouped by status. I am using my own dataset and I can't see any grouping happening. I have also tried using the test dataset and I also don't see that the samples get grouped. This is the code I am using, as provided in the Quick Start: 
```
data(immdata) 
gu = geneUsage(immdata$data)
vis(gu, .by="Status", .meta=immdata$meta) 
```
I don't see any difference by using the `.by="Status"` argument or not.

**Comment by vadimnazarov** [comment]
Hi, you need to pass the `.grid` argument:
```
data(immdata) 
gu = geneUsage(immdata$data)
vis(gu, .by="Status", .meta=immdata$meta, .grid=F)
```

**Comment by MaraLlamas** [comment]
It worked.
Thanks!!

**Comment by vadimnazarov** [comment]
Great!
