### ISSUE TITLE
Suggestions: provide a detailed description about clonotype definition model

### ISSUE THREAD

**Issue by YiweiNiu** [immunomind/immunarch#63]
## 📚 Documentation

Hi, I think it is necessary to have a doc for models of clonotype definitions, like the one in [scirpy](https://icbi-lab.github.io/scirpy/tcr-biology.html).

**Comment by vadimnazarov** [comment]
Hi @YiweiNiu , amazing suggestion, thank you a lot!

**Comment by vadimnazarov** [comment]
It will be implemented in the next version of Immunarch. More details are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
