### ISSUE TITLE
unreproducable results

### ISSUE THREAD

**Issue by decenwang** [immunomind/immunarch#69]
[https://immunarch.com/reference/public_matrix.html](url)
at last step, "head(pr.mat)" indicated not find object "pr.mat".

[https://immunarch.com/reference/pubRepApply.html](url)
at last step, "head(prapp)" indicated not find object "prapp".

[https://immunarch.com/reference/immunr_hclust.html](url)
might due to the changes of other package used in your package, the optimal number of clusters has changed, in your previous discription, the optimal number is 2, now, it is 4.

My R is 4.0.1

Cheers,

Decen

**Comment by vadimnazarov** [comment]
Hi @decenwang 

Thank you for noticing that! We are re-publishing the package on CRAN to make sure it compatible with the latest R 4.0.* update. Some of the function may not work before the release. The release should be available next week, we will create the GitHub release and post it on Twitter to notify. Feel free to "star" and "watch" and our repository to follow the latest updates here as well.

Feel free to try the development version, it should be compatible with the latest release, please. To install it, just execute the following command:
```r
devtools::install_github("immunomind/immunarch", ref="dev")
```

I will not close this issue until it's validated. If you encounter the same or similar errors on the development version, we can continue the conversation here.

Your help is much appreciated! Thank you!

**Comment by decenwang** [comment]
> Hi @decenwang
> 
> Thank you for noticing that! We are re-publishing the package on CRAN to make sure it compatible with the latest R 4.0.* update. Some of the function may not work before the release. The release should be available next week, we will create the GitHub release and post it on Twitter to notify. Feel free to "star" and "watch" our repository to follow the latest updates on GitHub as well.
> 
> Feel free to try the development version, it should be compatible with the latest release, please. To install it, just execute the following command:
> 
> ```r
> devtools::install_github("immunomind/immunarch", ref="dev")
> ```
> 
> I will not close this issue until it's validated. If you encounter the same or similar errors on the development version, we can continue the conversation here.
> 
> Your help is much appreciated! Thank you!

Hi Dr.Nazrarov,

Thanks a lot.
I also got another troubling when installing the "development" version. as below:
 **Failed to install 'immunarch' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed**
Anyway, I will wait for the new release, now I am using the old one for training.

Cheers,

Decen

**Comment by vadimnazarov** [comment]
Hi Decen,

It seems that there is an issue with the secured connection to GitHub. Can you download the attached package and try to apply `devtools::install_local` on it? You don't need to decompress the file, just provide the path to the archive.

[immunarch_0.6.5.tar.gz](https://github.com/immunomind/immunarch/files/4783401/immunarch_0.6.5.tar.gz)

**Comment by vadimnazarov** [comment]
It seems that immunarch 0.6.5 is already on CRAN, try this approach first!

**Comment by decenwang** [comment]
Hi Dr. Nazarov,

I appreciate your great help. Yesterday, I tried to install the 0.6.5, but after installation, I cannot use it, cannot library(immunarch). Luckily, I installed the 0.6.4 in our workstation in R3.6.0. So I copy all the R 3.6.0 into my laptop to use the 0.6.4. If you would like to "encounter" the problem and crack it, I suggest you copy your R beforehand to a new file as a backup. I am not a programmer, so I solve this trouble. When I finish my analysis, I prefer to giving some suggestions to improve the immunarch package, of course, the package is amazing now.  Thanks a lot!

Best!

Decen

**Comment by vadimnazarov** [comment]
Hi Decen,

I'm sorry for the inconvenience! The bug is still obscure to me. Would you be willing to share with me what commands did you execute to install and load immunarch, and what was the output in R console? It would greatly help the community, and we would be able to quickly resolve it so you won't be needed to copy the complete R library anymore!

**Comment by vadimnazarov** [comment]
Ping about the console commands
