### ISSUE TITLE
definition request

### ISSUE THREAD

**Issue by decenwang** [immunomind/immunarch#73]
Hi  Dr. Nazarov,

Forgive my unwiseness, I am still puzzled by some definitions, e.g.

in repOverlap() fucntion, [https://immunarch.com/reference/repOverlap.html](url)
**step** | Either an integer or a numeric vector.In the first case, the integer defines the step of incremental overlap.In the second case, the vector encodes all repertoire sampling depths.
-- | --
1. When and where I use the arguement ".step" ?  Does it display the overlapped clones between the "step".
2. And also, the method = "inc+morisita" or "inc+public". what does "incremental overlap" or "incremental" mean generally?
3. Generally, the mixcr may give more than one best v hit for a sequence, for example, TRBV4-1,TRBV4-3. In geneUsage(), there is an argument ".ambig" which can determine the first one will be chosen for analysis, while in pubRep(), there is no identical argument to do the same work, so if I set ".col" = "aa+v", how will it work? choose the first v segment or the second one? even if they belong to the same family.

Thanks a lot!

Best,

Decen

**Comment by vadimnazarov** [comment]
Hi Decen!

1 & 2. Yes, so in short you apply repOverlap at the the very first N clonotypes, where N is incrementally grows by .step. If .step is 1000, then you will have overlaps of the most abundant 1000, 2000, 3000, 4000, etc. clonotypes 

3. "aa+v" will work with full matches, so if a clonotype has "TRBV4-1, TRBV4-2", the full match of both segments is required to count this as an equal clonotype to a clonotype in another repertoire

Does it make sense, or would you like me to clarify something?

**Comment by decenwang** [comment]
> Hi Decen!
> 
> 1 & 2. Yes, so in short you apply repOverlap at the the very first N clonotypes, where N is incrementally grows by .step. If .step is 1000, then you will have overlaps of the most abundant 1000, 2000, 3000, 4000, etc. clonotypes
> 
> 1. "aa+v" will work with full matches, so if a clonotype has "TRBV4-1, TRBV4-2", the full match of both segments is required to count this as an equal clonotype to a clonotype in another repertoire
> 
> Does it make sense, or would you like me to clarify something?

Yes, thanks a lot. When it plots, it is a little bit weird, so I write a command to only choose the first segment, discarding the others. and in the manual of Mixcr, the author also mentioned sometimes more than one segment will be assigned, anyhow, the first one is the first place, and they are always in the same family.  I also really hope someday, immunarch can incorporate an function to output the fasta file, read by MEGA or MrBayes with designated variables (like case name/number, proportion, v gene name .etc.) 

Cheers,

Decen

**Comment by vadimnazarov** [comment]
Closing this issue for now. More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
