### ISSUE TITLE
import directly from seurat object

### ISSUE THREAD

**Issue by wfma** [immunomind/immunarch#77]
Hi! I was hoping you can provide some guidance on importing processed Seurat objects (that contains the metadata) directly into immunarch for exploration. 

I tried importing the .txt count matrices and the saved seurat .rds files with no luck. Here is the error I get when I tried:

```
> immdata <- repLoad("seuratobject.rds")  

== Step 1/3: loading repertoire files... ==


== Step 2/3: checking metadata files and merging files... ==

Processing "" ...
Error in parsed_batches[[batch_i]] : subscript out of bounds
> 

```
Any suggestions?

Thank you,
Wei

**Comment by vadimnazarov** [comment]
Hi @wfma ,

thank you for letting us know about the issue! The immunarch package is focused on the exploration of the immune repertoire data, i.e., clonotype tables, not gene expression data. So currently we don't support loading Seurat objects into immunarch. 

However, if you have clonotype tables separately from the Seurat object, you can easily upload them to the immunarch. What is your technology, is it 10X Genomics? If so, do you have "filtetered contigs annotations" files? This link may help: https://immunarch.com/articles/web_only/load_10x.html

**Comment by wfma** [comment]
I see! Thank you so much. Yes it is 10X. I will explore more and see what I can come up with.

Wei

**Comment by vadimnazarov** [comment]
Perfect, thank you! Yes, please let us know about any bugs or questions by opening the ticket here. Your input is much appreciated.

**Comment by kanefos** [comment]
Hi - I have a similar query. For reasons outside my control my working data is simply the CDR3 sequence of TRA and TRB chains, alongside cell and sample metadata. Is it possible to import such a minimalist dataset into immunarch? I simply want to do some basic clonality/diversity calculations and leverage your great plotting API. Thanks.

**Comment by vadimnazarov** [comment]
Closing this issue for now.  It will be implemented in the next version of Immunarch.

More details on the next version of Immunarch are here: https://b-t.cr/t/immunarch-will-significantly-evolve-but-it-will-break-things-and-we-need-your-help/1123
