### ISSUE TITLE
Error with repLoad function

### ISSUE THREAD

**Issue by PaniGopaluni** [immunomind/immunarch#8]
Hi,

When using repLoad function I am getting the following error:

immdata <- repLoad("MIXCR/ExportedClones")
Parsing MIXCR/ExportedClones ...
Parsing MIXCR/ExportedClones/metadata.txt -- metadata
Parsing MIXCR/ExportedClones/SLX-17310.i701_i502_tcr.clonotypes.ALL.txt -- mixcr
Error in `[[<-.data.frame`(`*tmp*`, .aa.seq, value = list()) : 
  replacement has 0 rows, data has 218
I am using immunarch version 0.3.3
Output files are from mixcr in .txt format.

I would appreciate it if you could help me to resolve this issue.

Kind regards
Pani

**Comment by vadimnazarov** [comment]
Hi, can you send me first 5-10 lines from your files that repLoad can't parse please? Email: vdm.nazarov at gmail 

We will update the parser then. Thank you!

**Comment by vadimnazarov** [comment]
The package is updated, please updat to the latest version 0.3.3.9003 and check it out.

**Comment by vadimnazarov** [comment]
Fixed in the latest version 0.3.3.9005.
