### ISSUE TITLE
Failed to load 10X VDJ data

### ISSUE THREAD

**Issue by crushseven-7** [immunomind/immunarch#92]
Hey there,
Currently, I got few scTCR-seq&scBCR-seq data. After I finished the cellranger vdj analysis, I tried to load the result into into immunarch. Howerever I got those error:
```
  -- Parsing "/B1/B1/outs/all_contig_annotations.csv" -- 10x (filt.contigs)
  [!] Removed 264 clonotypes with no nucleotide and amino acid CDR3 sequence.
  -- Parsing "/B1/B1/outs/all_contig_annotations.json" -- unsupported format, skipping
  -- Parsing "/B1/B1/outs/all_contig.bam.bai" -- unsupported format, skipping
  -- Parsing "/B1/outs/cell_barcodes.json" --   -- Parsing "/B1/B1/outs/clonotypes.csv" -- unsupported format, skipping
  -- Parsing "/B1/B1/outs/concat_ref.bam.bai" -- Error in tolower(l) : invalid multibyte string 1
```
I used Cellranger in version **3.1**, any suggestion?

**Comment by EugeneRumynskiy** [comment]
Hello @crushseven-7. What was the problem?
By the way we are running short 15m interviews with our user. Would you join us for a short talk about your experience with the package?

**Comment by crushseven-7** [comment]
Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch.  Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.

**Comment by EugeneRumynskiy** [comment]
No problems @crushseven-7, wish you a smooth and simple data loading :)

**Comment by Zifeng1995** [comment]
> Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch. Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.

Sorry to disturb you, I met the same error with you. Can you tell me your solution to this error?

**Comment by crushseven-7** [comment]
> > Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch. Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.
> 
> Sorry to disturb you, I met the same error with you. Can you tell me your solution to this error?

Sure. This error occured due to I set the directory to the cellranger output file.  The solution is you copyed your `all_contig_annotations.csv` to a fresh new directory. When you got multiple samples, you could also rename the file with your sample name.

**Comment by Zifeng1995** [comment]
> > > Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch. Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.
> > 
> > 
> > Sorry to disturb you, I met the same error with you. Can you tell me your solution to this error?
> 
> Sure. This error occured due to I set the directory to the cellranger output file. The solution is you copyed your `all_contig_annotations.csv` to a fresh new directory. When you got multiple samples, you could also rename the file with your sample name.

I got it. I checked my output file and found three files named `all_contig_annotations.csv` ,`filtered_contig_annotations.csv` ,`consensus_annotations.csv`. Should I input all these file per sample or just input  `filtered_contig_annotations.csv` ? Thanks for your help!

**Comment by crushseven-7** [comment]
> > > > Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch. Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.
> > > 
> > > 
> > > Sorry to disturb you, I met the same error with you. Can you tell me your solution to this error?
> > 
> > 
> > Sure. This error occured due to I set the directory to the cellranger output file. The solution is you copyed your `all_contig_annotations.csv` to a fresh new directory. When you got multiple samples, you could also rename the file with your sample name.
> 
> I got it. I checked my output file and found three files named `all_contig_annotations.csv` ,`filtered_contig_annotations.csv` ,`consensus_annotations.csv`. Should I input all these file per sample or just input `filtered_contig_annotations.csv` ? Thanks for your help!

I would only use `filtered_congtig_annotations.csv`  as input. As for the difference betweent each file you could check [cellranger instruction web](https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/output/annotation)

**Comment by Zifeng1995** [comment]
> > > > > Sorry for bothering, I just found I made a stupid mistake. Now I can load all my data into immunarch. Thank you very much for your invitation. I will choose a suitable time after calculating the mistiming.
> > > > 
> > > > 
> > > > Sorry to disturb you, I met the same error with you. Can you tell me your solution to this error?
> > > 
> > > 
> > > Sure. This error occured due to I set the directory to the cellranger output file. The solution is you copyed your `all_contig_annotations.csv` to a fresh new directory. When you got multiple samples, you could also rename the file with your sample name.
> > 
> > 
> > I got it. I checked my output file and found three files named `all_contig_annotations.csv` ,`filtered_contig_annotations.csv` ,`consensus_annotations.csv`. Should I input all these file per sample or just input `filtered_contig_annotations.csv` ? Thanks for your help!
> 
> I would only use `filtered_congtig_annotations.csv` as input. As for the difference betweent each file you could check [cellranger instruction web](https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/output/annotation)

Thank you for your answers!
