### ISSUE TITLE
TBAdb doesn't load 

### ISSUE THREAD

**Issue by nebskinner** [immunomind/immunarch#93]
## To Reproduce
1. If I use the gitlab path: 
tbadb = dbLoad("https://gitlab.com/immunomind/immunarch/raw/dev-0.5.0/private/TBAdb.xlsx", "tbadb", .species = "Homo Sapiens", .chain = "BCR", .pathology = "HCV")
2. Error: `path` does not exist: ‘https://gitlab.com/immunomind/immunarch/raw/dev-0.5.0/private/TBAdb.xlsx’
3. ***If instead I download the database to my computer first from PIRD:
tbadb = dbLoad(.path=~/Desktop/TBAdb.xlsx, .db="tbadb", .species = "Homo Sapiens", .chain = "BCR", .pathology = "HCV")
4. "Error in check_col_types(col_types) : is.character(col_types) is not TRUE"

**Comment by vadimnazarov** [comment]
Hi @nebskinner 

Thank you for using the package and letting us know about the issue! Our team appreciates it.

I got a different error. Can you send me a link where you downloaded the PIRD database? It is possible that they changed the database format, and we will need to rewrite parser for it. Thank you!

**Comment by nebskinner** [comment]
Thanks for your reply, @vadimnazarov. I downloaded the database from: https://db.cngb.org/pird/tbadb/.

I also tried re-installing Immunarch again -- I thought I had installed the latest version already but that must not have been what I was using because although it still doesn't work, the errors are different. When I use my downloaded database the error is: 
"Error in dbLoad(.path = "~/Desktop/TBAdb.xlsx", .db = "tbadb", .species = "Homo Sapiens",  :                                   
  Chain BCR not found in the input database. Check available chains in the database:
'TRA', 'TRA-TRB', 'TRB' "
This is true even though when I open the downloaded database, there is a BCR tab. 

If I use .chain = NA, the error is:
"Error in dbLoad(.path = "~/Desktop/TBAdb.xlsx", .db = "tbadb", .species = "Homo Sapiens",  : 
  TBAdb requires the .chain argument. Please specify it and try again."

When I try it using the link from the Immunarch website, the error is now:
"Error: `path` does not exist: ‘https://gitlab.com/immunomind/immunarch/raw/dev-0.5.0/private/TBAdb.xlsx’ "

Sorry for the confusion. Definitely should have double checked the version before posting. Do our errors now match?

**Comment by vadimnazarov** [comment]
Yes, thank you!

Try IG* instead of BCRs, e.g.:

```
immunarch::dbLoad("~/Downloads/TBAdb.xlsx", .db="tbadb", .species = "Homo Sapiens", .chain = "IGH", .pathology = "HCV")
```

But there is no HCV in the database, I think they named it differently. "Hepatitis C virus" I guess?

**Comment by nebskinner** [comment]
Yes, that works! Thank you!

**Comment by vadimnazarov** [comment]
My pleasure!
