### ISSUE TITLE
Function for ploting Treemap to display immune diversity

### ISSUE THREAD

**Issue by wanhui5867** [immunomind/immunarch#98]
Hi authors,

Thanks for such a nice tool! I just wonder that can we plot treemap for each sample. Treemap is a useful visualization to display immune diversity. If it is not including current, will you add it in the future?
![image](https://user-images.githubusercontent.com/31027318/89806067-dbc41880-db36-11ea-96aa-e9cb065a038b.png)

**Comment by vadimnazarov** [comment]
Hi @wanhui5867 

Thank you for your question! Sadly, we remove `treemap` from the package due to the uncommon usage of it. However, you can easily do it by yourself. Would you like to plot treemaps for gene usages, clonotype counts or something else? Please let me know and I will show you the code, it's very straightforward.

**Comment by wanhui5867** [comment]
Awesome! You're so nice that could give me the code. @vadimnazarov 

The treemap is intuitive to compare paired samples. I tried the treemap R package to plot, but the right-angle rectangle is not as pretty as the one I showed above. I think you might know a better one and can directly add it to immunarch.

I'd like to plot treemaps for clonotypes composition of each sample, for example, each rounded rectangle represents a unique entry: v+j+aa, and the size of a spot denotes the relative frequency. It would be better that the entire plot area is divided into sub-areas according to  V-usage, which is then subdivided according to  J-usage,  and then each  uCDR3  within a  given  V-J- the combination  is subsequently represented by a  rounded rectangle.  

If the code is not exactly what I expected, it is also OK that I can try to modify it by myself. 

Thanks in advance!

**Comment by vadimnazarov** [comment]
There are several packages for treemaps:
- https://github.com/wilkox/treemapify
- https://www.rdocumentation.org/packages/treemap/versions/2.4-2

Do you find the treemapify more appealing to you in constrast to treemap?

**Comment by wanhui5867** [comment]
The animated treemap looks interesting, thank you!

**Comment by vadimnazarov** [comment]
Good! Please let me know about any issues with treemap coding by re-opening this issue. I will be glad to figure out the R code for clonotype treemaps with you.
